// Code generated by Fern. DO NOT EDIT.

package downloads

import (
	context "context"

	platformgo "github.com/axilioai/platform-go"
	core "github.com/axilioai/platform-go/core"
	internal "github.com/axilioai/platform-go/internal"
	option "github.com/axilioai/platform-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns one page of the files captured off phones during sessions (AXI-1449), newest first. Each row carries its capture state: a skipped or failed capture is a visible entry with a reason, not an absence. Downloads share the library and its storage quota with uploads, and a ready download can be delivered to a phone by its id like any upload.
func (c *Client) List(
	ctx context.Context,
	request *platformgo.DownloadsListRequest,
	opts ...option.RequestOption,
) (*platformgo.FileDownloadListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Removes a captured file from the org's library and everywhere it was delivered: the stored object and the library entry go immediately, and every phone the file was pushed to is scheduled to remove its copy (removal is confirmed per phone and retried until it lands), the same recall an upload's delete runs. The response reports how many phones that recall reaches. The source phone's own copy from the capture session is outside the recall: it belongs to the session, not the library.
func (c *Client) Delete(
	ctx context.Context,
	request *platformgo.DownloadsDeleteRequest,
	opts ...option.RequestOption,
) (*platformgo.DeleteFileOutputBody, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the files this session captured off its phone, newest first — the direct answer to "what did this session download". Rows appear at detection, before the bytes finish moving, so a caller waiting on a file watches its capture state progress rather than an empty list.
func (c *Client) PhonesSessionDownloads(
	ctx context.Context,
	request *platformgo.PhonesSessionDownloadsRequest,
	opts ...option.RequestOption,
) (*platformgo.FileDownloadListResponse, error) {
	response, err := c.WithRawResponse.PhonesSessionDownloads(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
