// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/axilioai/platform-go/internal"
	big "math/big"
	time "time"
)

var (
	downloadsDeleteRequestFieldDownloadID = big.NewInt(1 << 0)
)

type DownloadsDeleteRequest struct {
	// download identifier to delete
	DownloadID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DownloadsDeleteRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetDownloadID sets the DownloadID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadsDeleteRequest) SetDownloadID(downloadID string) {
	d.DownloadID = downloadID
	d.require(downloadsDeleteRequestFieldDownloadID)
}

var (
	downloadsListRequestFieldQ             = big.NewInt(1 << 0)
	downloadsListRequestFieldMimeType      = big.NewInt(1 << 1)
	downloadsListRequestFieldMinSizeBytes  = big.NewInt(1 << 2)
	downloadsListRequestFieldMaxSizeBytes  = big.NewInt(1 << 3)
	downloadsListRequestFieldCreatedAfter  = big.NewInt(1 << 4)
	downloadsListRequestFieldCreatedBefore = big.NewInt(1 << 5)
	downloadsListRequestFieldLimit         = big.NewInt(1 << 6)
	downloadsListRequestFieldOffset        = big.NewInt(1 << 7)
	downloadsListRequestFieldSessionID     = big.NewInt(1 << 8)
	downloadsListRequestFieldSort          = big.NewInt(1 << 9)
	downloadsListRequestFieldOrder         = big.NewInt(1 << 10)
)

type DownloadsListRequest struct {
	// filter by filename, case-insensitive substring match
	Q *string `json:"-" url:"q,omitempty"`
	// only downloads of exactly this media type
	MimeType *string `json:"-" url:"mime_type,omitempty"`
	// only downloads at least this many bytes (0 = no bound)
	MinSizeBytes *int64 `json:"-" url:"min_size_bytes,omitempty"`
	// only downloads at most this many bytes (0 = no bound)
	MaxSizeBytes *int64 `json:"-" url:"max_size_bytes,omitempty"`
	// only downloads registered at or after this time (RFC 3339)
	CreatedAfter *time.Time `json:"-" url:"created_after,omitempty"`
	// only downloads registered at or before this time (RFC 3339)
	CreatedBefore *time.Time `json:"-" url:"created_before,omitempty"`
	// max items per page
	Limit *int64 `json:"-" url:"limit,omitempty"`
	// pagination offset
	Offset *int64 `json:"-" url:"offset,omitempty"`
	// only downloads captured by this session
	SessionID *string `json:"-" url:"session_id,omitempty"`
	// field to sort by
	Sort *DownloadsListRequestSort `json:"-" url:"sort,omitempty"`
	// sort direction
	Order *DownloadsListRequestOrder `json:"-" url:"order,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DownloadsListRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadsListRequest) SetQ(q *string) {
	d.Q = q
	d.require(downloadsListRequestFieldQ)
}

// SetMimeType sets the MimeType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadsListRequest) SetMimeType(mimeType *string) {
	d.MimeType = mimeType
	d.require(downloadsListRequestFieldMimeType)
}

// SetMinSizeBytes sets the MinSizeBytes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadsListRequest) SetMinSizeBytes(minSizeBytes *int64) {
	d.MinSizeBytes = minSizeBytes
	d.require(downloadsListRequestFieldMinSizeBytes)
}

// SetMaxSizeBytes sets the MaxSizeBytes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadsListRequest) SetMaxSizeBytes(maxSizeBytes *int64) {
	d.MaxSizeBytes = maxSizeBytes
	d.require(downloadsListRequestFieldMaxSizeBytes)
}

// SetCreatedAfter sets the CreatedAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadsListRequest) SetCreatedAfter(createdAfter *time.Time) {
	d.CreatedAfter = createdAfter
	d.require(downloadsListRequestFieldCreatedAfter)
}

// SetCreatedBefore sets the CreatedBefore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadsListRequest) SetCreatedBefore(createdBefore *time.Time) {
	d.CreatedBefore = createdBefore
	d.require(downloadsListRequestFieldCreatedBefore)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadsListRequest) SetLimit(limit *int64) {
	d.Limit = limit
	d.require(downloadsListRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadsListRequest) SetOffset(offset *int64) {
	d.Offset = offset
	d.require(downloadsListRequestFieldOffset)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadsListRequest) SetSessionID(sessionID *string) {
	d.SessionID = sessionID
	d.require(downloadsListRequestFieldSessionID)
}

// SetSort sets the Sort field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadsListRequest) SetSort(sort *DownloadsListRequestSort) {
	d.Sort = sort
	d.require(downloadsListRequestFieldSort)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DownloadsListRequest) SetOrder(order *DownloadsListRequestOrder) {
	d.Order = order
	d.require(downloadsListRequestFieldOrder)
}

var (
	phonesSessionDownloadsRequestFieldSessionID     = big.NewInt(1 << 0)
	phonesSessionDownloadsRequestFieldQ             = big.NewInt(1 << 1)
	phonesSessionDownloadsRequestFieldMimeType      = big.NewInt(1 << 2)
	phonesSessionDownloadsRequestFieldMinSizeBytes  = big.NewInt(1 << 3)
	phonesSessionDownloadsRequestFieldMaxSizeBytes  = big.NewInt(1 << 4)
	phonesSessionDownloadsRequestFieldCreatedAfter  = big.NewInt(1 << 5)
	phonesSessionDownloadsRequestFieldCreatedBefore = big.NewInt(1 << 6)
	phonesSessionDownloadsRequestFieldLimit         = big.NewInt(1 << 7)
	phonesSessionDownloadsRequestFieldOffset        = big.NewInt(1 << 8)
)

type PhonesSessionDownloadsRequest struct {
	// session whose captures to list
	SessionID string `json:"-" url:"-"`
	// filter by filename, case-insensitive substring match
	Q *string `json:"-" url:"q,omitempty"`
	// only downloads of exactly this media type
	MimeType *string `json:"-" url:"mime_type,omitempty"`
	// only downloads at least this many bytes (0 = no bound)
	MinSizeBytes *int64 `json:"-" url:"min_size_bytes,omitempty"`
	// only downloads at most this many bytes (0 = no bound)
	MaxSizeBytes *int64 `json:"-" url:"max_size_bytes,omitempty"`
	// only downloads registered at or after this time (RFC 3339)
	CreatedAfter *time.Time `json:"-" url:"created_after,omitempty"`
	// only downloads registered at or before this time (RFC 3339)
	CreatedBefore *time.Time `json:"-" url:"created_before,omitempty"`
	// max items per page
	Limit *int64 `json:"-" url:"limit,omitempty"`
	// pagination offset
	Offset *int64 `json:"-" url:"offset,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PhonesSessionDownloadsRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhonesSessionDownloadsRequest) SetSessionID(sessionID string) {
	p.SessionID = sessionID
	p.require(phonesSessionDownloadsRequestFieldSessionID)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhonesSessionDownloadsRequest) SetQ(q *string) {
	p.Q = q
	p.require(phonesSessionDownloadsRequestFieldQ)
}

// SetMimeType sets the MimeType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhonesSessionDownloadsRequest) SetMimeType(mimeType *string) {
	p.MimeType = mimeType
	p.require(phonesSessionDownloadsRequestFieldMimeType)
}

// SetMinSizeBytes sets the MinSizeBytes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhonesSessionDownloadsRequest) SetMinSizeBytes(minSizeBytes *int64) {
	p.MinSizeBytes = minSizeBytes
	p.require(phonesSessionDownloadsRequestFieldMinSizeBytes)
}

// SetMaxSizeBytes sets the MaxSizeBytes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhonesSessionDownloadsRequest) SetMaxSizeBytes(maxSizeBytes *int64) {
	p.MaxSizeBytes = maxSizeBytes
	p.require(phonesSessionDownloadsRequestFieldMaxSizeBytes)
}

// SetCreatedAfter sets the CreatedAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhonesSessionDownloadsRequest) SetCreatedAfter(createdAfter *time.Time) {
	p.CreatedAfter = createdAfter
	p.require(phonesSessionDownloadsRequestFieldCreatedAfter)
}

// SetCreatedBefore sets the CreatedBefore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhonesSessionDownloadsRequest) SetCreatedBefore(createdBefore *time.Time) {
	p.CreatedBefore = createdBefore
	p.require(phonesSessionDownloadsRequestFieldCreatedBefore)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhonesSessionDownloadsRequest) SetLimit(limit *int64) {
	p.Limit = limit
	p.require(phonesSessionDownloadsRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhonesSessionDownloadsRequest) SetOffset(offset *int64) {
	p.Offset = offset
	p.require(phonesSessionDownloadsRequestFieldOffset)
}

// One page of the org's captured downloads.
var (
	fileDownloadListResponseFieldSchema    = big.NewInt(1 << 0)
	fileDownloadListResponseFieldDownloads = big.NewInt(1 << 1)
	fileDownloadListResponseFieldTotal     = big.NewInt(1 << 2)
)

type FileDownloadListResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Captured files, newest first.
	Downloads []*FileDownloadSummary `json:"downloads,omitempty" url:"downloads,omitempty"`
	// Total downloads matching the query.
	Total int64 `json:"total" url:"total"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FileDownloadListResponse) GetSchema() *string {
	if f == nil {
		return nil
	}
	return f.Schema
}

func (f *FileDownloadListResponse) GetDownloads() []*FileDownloadSummary {
	if f == nil {
		return nil
	}
	return f.Downloads
}

func (f *FileDownloadListResponse) GetTotal() int64 {
	if f == nil {
		return 0
	}
	return f.Total
}

func (f *FileDownloadListResponse) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FileDownloadListResponse) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadListResponse) SetSchema(schema *string) {
	f.Schema = schema
	f.require(fileDownloadListResponseFieldSchema)
}

// SetDownloads sets the Downloads field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadListResponse) SetDownloads(downloads []*FileDownloadSummary) {
	f.Downloads = downloads
	f.require(fileDownloadListResponseFieldDownloads)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadListResponse) SetTotal(total int64) {
	f.Total = total
	f.require(fileDownloadListResponseFieldTotal)
}

func (f *FileDownloadListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler FileDownloadListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FileDownloadListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FileDownloadListResponse) MarshalJSON() ([]byte, error) {
	type embed FileDownloadListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FileDownloadListResponse) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// One file captured off a phone during a session.
var (
	fileDownloadSummaryFieldAttachmentURL    = big.NewInt(1 << 0)
	fileDownloadSummaryFieldBytesTransferred = big.NewInt(1 << 1)
	fileDownloadSummaryFieldCaptureError     = big.NewInt(1 << 2)
	fileDownloadSummaryFieldCaptureState     = big.NewInt(1 << 3)
	fileDownloadSummaryFieldChecksum         = big.NewInt(1 << 4)
	fileDownloadSummaryFieldCreatedAt        = big.NewInt(1 << 5)
	fileDownloadSummaryFieldDownloadURL      = big.NewInt(1 << 6)
	fileDownloadSummaryFieldDurationSeconds  = big.NewInt(1 << 7)
	fileDownloadSummaryFieldFilename         = big.NewInt(1 << 8)
	fileDownloadSummaryFieldHeight           = big.NewInt(1 << 9)
	fileDownloadSummaryFieldID               = big.NewInt(1 << 10)
	fileDownloadSummaryFieldMimeType         = big.NewInt(1 << 11)
	fileDownloadSummaryFieldOnPhoneCount     = big.NewInt(1 << 12)
	fileDownloadSummaryFieldPreviewState     = big.NewInt(1 << 13)
	fileDownloadSummaryFieldReelURL          = big.NewInt(1 << 14)
	fileDownloadSummaryFieldSessionID        = big.NewInt(1 << 15)
	fileDownloadSummaryFieldSizeBytes        = big.NewInt(1 << 16)
	fileDownloadSummaryFieldThumbnailURL     = big.NewInt(1 << 17)
	fileDownloadSummaryFieldWidth            = big.NewInt(1 << 18)
)

type FileDownloadSummary struct {
	// Short-lived signed URL that downloads the file as an attachment under its name. Present only for ready captures.
	AttachmentURL *string `json:"attachment_url,omitempty" url:"attachment_url,omitempty"`
	// Bytes moved so far for an in-flight phone transfer. Absent until the phone reports progress.
	BytesTransferred *int64 `json:"bytes_transferred,omitempty" url:"bytes_transferred,omitempty"`
	// Reason the capture failed, when it did.
	CaptureError *string `json:"capture_error,omitempty" url:"capture_error,omitempty"`
	// Capture lifecycle: detected/uploading while in flight, ready when usable, or a terminal skip/failure with its reason recorded.
	CaptureState FileDownloadSummaryCaptureState `json:"capture_state" url:"capture_state"`
	// SHA-256 of the file's bytes, computed on the phone during upload.
	Checksum *string `json:"checksum,omitempty" url:"checksum,omitempty"`
	// When the capture was detected and registered.
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// Short-lived signed URL to read the file's bytes. Present only for ready captures; re-list to refresh an expired one.
	DownloadURL *string `json:"download_url,omitempty" url:"download_url,omitempty"`
	// Video duration in seconds.
	DurationSeconds *int64 `json:"duration_seconds,omitempty" url:"duration_seconds,omitempty"`
	// Filename as it appeared on the phone.
	Filename string `json:"filename" url:"filename"`
	// Intrinsic pixel height of the source.
	Height *int64 `json:"height,omitempty" url:"height,omitempty"`
	// File identifier. Unique across uploads and downloads; deliverable either way.
	ID string `json:"id" url:"id"`
	// Media type reported by the phone.
	MimeType string `json:"mime_type" url:"mime_type"`
	// Distinct phones currently holding or receiving a copy. Deleting the file recalls these.
	OnPhoneCount int64 `json:"on_phone_count" url:"on_phone_count"`
	// Whether the preview exists, is still being generated, or will never be available for this format.
	PreviewState FileDownloadSummaryPreviewState `json:"preview_state" url:"preview_state"`
	// Short-lived signed URL for the animated hover preview. Videos only; absent until generated.
	ReelURL *string `json:"reel_url,omitempty" url:"reel_url,omitempty"`
	// Session that produced the file.
	SessionID *string `json:"session_id,omitempty" url:"session_id,omitempty"`
	// Size in bytes, as reported at detection.
	SizeBytes int64 `json:"size_bytes" url:"size_bytes"`
	// Short-lived signed URL for the generated preview image. Absent while generation is pending, and permanently absent for formats without a preview.
	ThumbnailURL *string `json:"thumbnail_url,omitempty" url:"thumbnail_url,omitempty"`
	// Intrinsic pixel width of the source.
	Width *int64 `json:"width,omitempty" url:"width,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FileDownloadSummary) GetAttachmentURL() *string {
	if f == nil {
		return nil
	}
	return f.AttachmentURL
}

func (f *FileDownloadSummary) GetBytesTransferred() *int64 {
	if f == nil {
		return nil
	}
	return f.BytesTransferred
}

func (f *FileDownloadSummary) GetCaptureError() *string {
	if f == nil {
		return nil
	}
	return f.CaptureError
}

func (f *FileDownloadSummary) GetCaptureState() FileDownloadSummaryCaptureState {
	if f == nil {
		return ""
	}
	return f.CaptureState
}

func (f *FileDownloadSummary) GetChecksum() *string {
	if f == nil {
		return nil
	}
	return f.Checksum
}

func (f *FileDownloadSummary) GetCreatedAt() time.Time {
	if f == nil {
		return time.Time{}
	}
	return f.CreatedAt
}

func (f *FileDownloadSummary) GetDownloadURL() *string {
	if f == nil {
		return nil
	}
	return f.DownloadURL
}

func (f *FileDownloadSummary) GetDurationSeconds() *int64 {
	if f == nil {
		return nil
	}
	return f.DurationSeconds
}

func (f *FileDownloadSummary) GetFilename() string {
	if f == nil {
		return ""
	}
	return f.Filename
}

func (f *FileDownloadSummary) GetHeight() *int64 {
	if f == nil {
		return nil
	}
	return f.Height
}

func (f *FileDownloadSummary) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FileDownloadSummary) GetMimeType() string {
	if f == nil {
		return ""
	}
	return f.MimeType
}

func (f *FileDownloadSummary) GetOnPhoneCount() int64 {
	if f == nil {
		return 0
	}
	return f.OnPhoneCount
}

func (f *FileDownloadSummary) GetPreviewState() FileDownloadSummaryPreviewState {
	if f == nil {
		return ""
	}
	return f.PreviewState
}

func (f *FileDownloadSummary) GetReelURL() *string {
	if f == nil {
		return nil
	}
	return f.ReelURL
}

func (f *FileDownloadSummary) GetSessionID() *string {
	if f == nil {
		return nil
	}
	return f.SessionID
}

func (f *FileDownloadSummary) GetSizeBytes() int64 {
	if f == nil {
		return 0
	}
	return f.SizeBytes
}

func (f *FileDownloadSummary) GetThumbnailURL() *string {
	if f == nil {
		return nil
	}
	return f.ThumbnailURL
}

func (f *FileDownloadSummary) GetWidth() *int64 {
	if f == nil {
		return nil
	}
	return f.Width
}

func (f *FileDownloadSummary) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FileDownloadSummary) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetAttachmentURL sets the AttachmentURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetAttachmentURL(attachmentURL *string) {
	f.AttachmentURL = attachmentURL
	f.require(fileDownloadSummaryFieldAttachmentURL)
}

// SetBytesTransferred sets the BytesTransferred field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetBytesTransferred(bytesTransferred *int64) {
	f.BytesTransferred = bytesTransferred
	f.require(fileDownloadSummaryFieldBytesTransferred)
}

// SetCaptureError sets the CaptureError field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetCaptureError(captureError *string) {
	f.CaptureError = captureError
	f.require(fileDownloadSummaryFieldCaptureError)
}

// SetCaptureState sets the CaptureState field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetCaptureState(captureState FileDownloadSummaryCaptureState) {
	f.CaptureState = captureState
	f.require(fileDownloadSummaryFieldCaptureState)
}

// SetChecksum sets the Checksum field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetChecksum(checksum *string) {
	f.Checksum = checksum
	f.require(fileDownloadSummaryFieldChecksum)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetCreatedAt(createdAt time.Time) {
	f.CreatedAt = createdAt
	f.require(fileDownloadSummaryFieldCreatedAt)
}

// SetDownloadURL sets the DownloadURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetDownloadURL(downloadURL *string) {
	f.DownloadURL = downloadURL
	f.require(fileDownloadSummaryFieldDownloadURL)
}

// SetDurationSeconds sets the DurationSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetDurationSeconds(durationSeconds *int64) {
	f.DurationSeconds = durationSeconds
	f.require(fileDownloadSummaryFieldDurationSeconds)
}

// SetFilename sets the Filename field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetFilename(filename string) {
	f.Filename = filename
	f.require(fileDownloadSummaryFieldFilename)
}

// SetHeight sets the Height field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetHeight(height *int64) {
	f.Height = height
	f.require(fileDownloadSummaryFieldHeight)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetID(id string) {
	f.ID = id
	f.require(fileDownloadSummaryFieldID)
}

// SetMimeType sets the MimeType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetMimeType(mimeType string) {
	f.MimeType = mimeType
	f.require(fileDownloadSummaryFieldMimeType)
}

// SetOnPhoneCount sets the OnPhoneCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetOnPhoneCount(onPhoneCount int64) {
	f.OnPhoneCount = onPhoneCount
	f.require(fileDownloadSummaryFieldOnPhoneCount)
}

// SetPreviewState sets the PreviewState field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetPreviewState(previewState FileDownloadSummaryPreviewState) {
	f.PreviewState = previewState
	f.require(fileDownloadSummaryFieldPreviewState)
}

// SetReelURL sets the ReelURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetReelURL(reelURL *string) {
	f.ReelURL = reelURL
	f.require(fileDownloadSummaryFieldReelURL)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetSessionID(sessionID *string) {
	f.SessionID = sessionID
	f.require(fileDownloadSummaryFieldSessionID)
}

// SetSizeBytes sets the SizeBytes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetSizeBytes(sizeBytes int64) {
	f.SizeBytes = sizeBytes
	f.require(fileDownloadSummaryFieldSizeBytes)
}

// SetThumbnailURL sets the ThumbnailURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetThumbnailURL(thumbnailURL *string) {
	f.ThumbnailURL = thumbnailURL
	f.require(fileDownloadSummaryFieldThumbnailURL)
}

// SetWidth sets the Width field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileDownloadSummary) SetWidth(width *int64) {
	f.Width = width
	f.require(fileDownloadSummaryFieldWidth)
}

func (f *FileDownloadSummary) UnmarshalJSON(data []byte) error {
	type embed FileDownloadSummary
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*f),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*f = FileDownloadSummary(unmarshaler.embed)
	f.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FileDownloadSummary) MarshalJSON() ([]byte, error) {
	type embed FileDownloadSummary
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed:     embed(*f),
		CreatedAt: internal.NewDateTime(f.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FileDownloadSummary) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Capture lifecycle: detected/uploading while in flight, ready when usable, or a terminal skip/failure with its reason recorded.
type FileDownloadSummaryCaptureState string

const (
	FileDownloadSummaryCaptureStateDetected        FileDownloadSummaryCaptureState = "detected"
	FileDownloadSummaryCaptureStateUploading       FileDownloadSummaryCaptureState = "uploading"
	FileDownloadSummaryCaptureStateReady           FileDownloadSummaryCaptureState = "ready"
	FileDownloadSummaryCaptureStateSkippedSize     FileDownloadSummaryCaptureState = "skipped_size"
	FileDownloadSummaryCaptureStateSkippedQuota    FileDownloadSummaryCaptureState = "skipped_quota"
	FileDownloadSummaryCaptureStateSkippedType     FileDownloadSummaryCaptureState = "skipped_type"
	FileDownloadSummaryCaptureStateDroppedTeardown FileDownloadSummaryCaptureState = "dropped_teardown"
	FileDownloadSummaryCaptureStateFailed          FileDownloadSummaryCaptureState = "failed"
)

func NewFileDownloadSummaryCaptureStateFromString(s string) (FileDownloadSummaryCaptureState, error) {
	switch s {
	case "detected":
		return FileDownloadSummaryCaptureStateDetected, nil
	case "uploading":
		return FileDownloadSummaryCaptureStateUploading, nil
	case "ready":
		return FileDownloadSummaryCaptureStateReady, nil
	case "skipped_size":
		return FileDownloadSummaryCaptureStateSkippedSize, nil
	case "skipped_quota":
		return FileDownloadSummaryCaptureStateSkippedQuota, nil
	case "skipped_type":
		return FileDownloadSummaryCaptureStateSkippedType, nil
	case "dropped_teardown":
		return FileDownloadSummaryCaptureStateDroppedTeardown, nil
	case "failed":
		return FileDownloadSummaryCaptureStateFailed, nil
	}
	var t FileDownloadSummaryCaptureState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (f FileDownloadSummaryCaptureState) Ptr() *FileDownloadSummaryCaptureState {
	return &f
}

// Whether the preview exists, is still being generated, or will never be available for this format.
type FileDownloadSummaryPreviewState string

const (
	FileDownloadSummaryPreviewStateProcessing  FileDownloadSummaryPreviewState = "processing"
	FileDownloadSummaryPreviewStateReady       FileDownloadSummaryPreviewState = "ready"
	FileDownloadSummaryPreviewStateUnavailable FileDownloadSummaryPreviewState = "unavailable"
)

func NewFileDownloadSummaryPreviewStateFromString(s string) (FileDownloadSummaryPreviewState, error) {
	switch s {
	case "processing":
		return FileDownloadSummaryPreviewStateProcessing, nil
	case "ready":
		return FileDownloadSummaryPreviewStateReady, nil
	case "unavailable":
		return FileDownloadSummaryPreviewStateUnavailable, nil
	}
	var t FileDownloadSummaryPreviewState
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (f FileDownloadSummaryPreviewState) Ptr() *FileDownloadSummaryPreviewState {
	return &f
}

// sort direction
type DownloadsListRequestOrder string

const (
	DownloadsListRequestOrderAsc  DownloadsListRequestOrder = "asc"
	DownloadsListRequestOrderDesc DownloadsListRequestOrder = "desc"
)

func NewDownloadsListRequestOrderFromString(s string) (DownloadsListRequestOrder, error) {
	switch s {
	case "asc":
		return DownloadsListRequestOrderAsc, nil
	case "desc":
		return DownloadsListRequestOrderDesc, nil
	}
	var t DownloadsListRequestOrder
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DownloadsListRequestOrder) Ptr() *DownloadsListRequestOrder {
	return &d
}

// field to sort by
type DownloadsListRequestSort string

const (
	DownloadsListRequestSortCreatedAt DownloadsListRequestSort = "created_at"
	DownloadsListRequestSortFilename  DownloadsListRequestSort = "filename"
	DownloadsListRequestSortSizeBytes DownloadsListRequestSort = "size_bytes"
)

func NewDownloadsListRequestSortFromString(s string) (DownloadsListRequestSort, error) {
	switch s {
	case "created_at":
		return DownloadsListRequestSortCreatedAt, nil
	case "filename":
		return DownloadsListRequestSortFilename, nil
	case "size_bytes":
		return DownloadsListRequestSortSizeBytes, nil
	}
	var t DownloadsListRequestSort
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DownloadsListRequestSort) Ptr() *DownloadsListRequestSort {
	return &d
}
