// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/axilioai/platform-go/internal"
	big "math/big"
	time "time"
)

var (
	runsCancelRequestFieldRunID = big.NewInt(1 << 0)
)

type RunsCancelRequest struct {
	// run identifier
	RunID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RunsCancelRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunsCancelRequest) SetRunID(runID string) {
	r.RunID = runID
	r.require(runsCancelRequestFieldRunID)
}

var (
	runCreateRequestFieldWorkflowID          = big.NewInt(1 << 0)
	runCreateRequestFieldRuns                = big.NewInt(1 << 1)
	runCreateRequestFieldStartTimeoutSeconds = big.NewInt(1 << 2)
)

type RunCreateRequest struct {
	// workflow to create runs for
	WorkflowID string `json:"-" url:"-"`
	// Per-run variable configurations. One run is created per entry.
	Runs []*RunConfig `json:"runs,omitempty" url:"-"`
	// How long a queued run may wait for a phone before it is auto-cancelled.
	StartTimeoutSeconds *int64 `json:"start_timeout_seconds,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RunCreateRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunCreateRequest) SetWorkflowID(workflowID string) {
	r.WorkflowID = workflowID
	r.require(runCreateRequestFieldWorkflowID)
}

// SetRuns sets the Runs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunCreateRequest) SetRuns(runs []*RunConfig) {
	r.Runs = runs
	r.require(runCreateRequestFieldRuns)
}

// SetStartTimeoutSeconds sets the StartTimeoutSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunCreateRequest) SetStartTimeoutSeconds(startTimeoutSeconds *int64) {
	r.StartTimeoutSeconds = startTimeoutSeconds
	r.require(runCreateRequestFieldStartTimeoutSeconds)
}

func (r *RunCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RunCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RunCreateRequest(body)
	return nil
}

func (r *RunCreateRequest) MarshalJSON() ([]byte, error) {
	type embed RunCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	runsGetRequestFieldRunID = big.NewInt(1 << 0)
)

type RunsGetRequest struct {
	// run identifier
	RunID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RunsGetRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunsGetRequest) SetRunID(runID string) {
	r.RunID = runID
	r.require(runsGetRequestFieldRunID)
}

var (
	runListRequestFieldLimit         = big.NewInt(1 << 0)
	runListRequestFieldOffset        = big.NewInt(1 << 1)
	runListRequestFieldSearch        = big.NewInt(1 << 2)
	runListRequestFieldSortBy        = big.NewInt(1 << 3)
	runListRequestFieldStatusFilter  = big.NewInt(1 << 4)
	runListRequestFieldTriggerFilter = big.NewInt(1 << 5)
	runListRequestFieldWorkflowID    = big.NewInt(1 << 6)
)

type RunListRequest struct {
	// Maximum number of runs to return per page.
	Limit *int64 `json:"limit,omitempty" url:"-"`
	// Pagination offset.
	Offset *int64 `json:"offset,omitempty" url:"-"`
	// Filters by run ID substring.
	Search *string `json:"search,omitempty" url:"-"`
	// Ordered list of sort specs; first entry is primary.
	SortBy []*RunSortSpec `json:"sort_by,omitempty" url:"-"`
	// StatusFilter restricts results to runs in the given statuses.
	StatusFilter []RunListRequestStatusFilterItem `json:"status_filter,omitempty" url:"-"`
	// TriggerFilter restricts results to runs with the given triggers.
	TriggerFilter []RunListRequestTriggerFilterItem `json:"trigger_filter,omitempty" url:"-"`
	// Filters results to a single workflow.
	WorkflowID *string `json:"workflow_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RunListRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunListRequest) SetLimit(limit *int64) {
	r.Limit = limit
	r.require(runListRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunListRequest) SetOffset(offset *int64) {
	r.Offset = offset
	r.require(runListRequestFieldOffset)
}

// SetSearch sets the Search field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunListRequest) SetSearch(search *string) {
	r.Search = search
	r.require(runListRequestFieldSearch)
}

// SetSortBy sets the SortBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunListRequest) SetSortBy(sortBy []*RunSortSpec) {
	r.SortBy = sortBy
	r.require(runListRequestFieldSortBy)
}

// SetStatusFilter sets the StatusFilter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunListRequest) SetStatusFilter(statusFilter []RunListRequestStatusFilterItem) {
	r.StatusFilter = statusFilter
	r.require(runListRequestFieldStatusFilter)
}

// SetTriggerFilter sets the TriggerFilter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunListRequest) SetTriggerFilter(triggerFilter []RunListRequestTriggerFilterItem) {
	r.TriggerFilter = triggerFilter
	r.require(runListRequestFieldTriggerFilter)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunListRequest) SetWorkflowID(workflowID *string) {
	r.WorkflowID = workflowID
	r.require(runListRequestFieldWorkflowID)
}

func (r *RunListRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RunListRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RunListRequest(body)
	return nil
}

func (r *RunListRequest) MarshalJSON() ([]byte, error) {
	type embed RunListRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	runEventsRequestFieldEventTypes = big.NewInt(1 << 0)
	runEventsRequestFieldLimit      = big.NewInt(1 << 1)
	runEventsRequestFieldOffset     = big.NewInt(1 << 2)
	runEventsRequestFieldSessionID  = big.NewInt(1 << 3)
)

type RunEventsRequest struct {
	// EventTypes restricts results to specific event type codes (RUN_STARTED / OUTPUT_LOG / SDK_CALL_COMPLETED / etc.).
	EventTypes []string `json:"event_types,omitempty" url:"-"`
	// Maximum number of events to return.
	Limit int64 `json:"limit" url:"-"`
	// Pagination offset.
	Offset int64 `json:"offset" url:"-"`
	// Filters events to a specific device session (formerly allocation_id; W6-2).
	SessionID string `json:"session_id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RunEventsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetEventTypes sets the EventTypes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventsRequest) SetEventTypes(eventTypes []string) {
	r.EventTypes = eventTypes
	r.require(runEventsRequestFieldEventTypes)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventsRequest) SetLimit(limit int64) {
	r.Limit = limit
	r.require(runEventsRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventsRequest) SetOffset(offset int64) {
	r.Offset = offset
	r.require(runEventsRequestFieldOffset)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventsRequest) SetSessionID(sessionID string) {
	r.SessionID = sessionID
	r.require(runEventsRequestFieldSessionID)
}

func (r *RunEventsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RunEventsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RunEventsRequest(body)
	return nil
}

func (r *RunEventsRequest) MarshalJSON() ([]byte, error) {
	type embed RunEventsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	runHistoryRequestFieldEndDate      = big.NewInt(1 << 0)
	runHistoryRequestFieldLimit        = big.NewInt(1 << 1)
	runHistoryRequestFieldOffset       = big.NewInt(1 << 2)
	runHistoryRequestFieldSearch       = big.NewInt(1 << 3)
	runHistoryRequestFieldStartDate    = big.NewInt(1 << 4)
	runHistoryRequestFieldStatusFilter = big.NewInt(1 << 5)
	runHistoryRequestFieldWorkflowID   = big.NewInt(1 << 6)
)

type RunHistoryRequest struct {
	// End of the query time window.
	EndDate time.Time `json:"end_date" url:"-"`
	// Maximum number of runs to return.
	Limit int64 `json:"limit" url:"-"`
	// Pagination offset.
	Offset int64 `json:"offset" url:"-"`
	// Filters by run ID or workflow ID substring.
	Search *string `json:"search,omitempty" url:"-"`
	// Beginning of the query time window.
	StartDate time.Time `json:"start_date" url:"-"`
	// Restricts results to runs in the given statuses (case-insensitive).
	StatusFilter []RunHistoryRequestStatusFilterItem `json:"status_filter,omitempty" url:"-"`
	// Filters results to a single workflow.
	WorkflowID *string `json:"workflow_id,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RunHistoryRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetEndDate sets the EndDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryRequest) SetEndDate(endDate time.Time) {
	r.EndDate = endDate
	r.require(runHistoryRequestFieldEndDate)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryRequest) SetLimit(limit int64) {
	r.Limit = limit
	r.require(runHistoryRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryRequest) SetOffset(offset int64) {
	r.Offset = offset
	r.require(runHistoryRequestFieldOffset)
}

// SetSearch sets the Search field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryRequest) SetSearch(search *string) {
	r.Search = search
	r.require(runHistoryRequestFieldSearch)
}

// SetStartDate sets the StartDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryRequest) SetStartDate(startDate time.Time) {
	r.StartDate = startDate
	r.require(runHistoryRequestFieldStartDate)
}

// SetStatusFilter sets the StatusFilter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryRequest) SetStatusFilter(statusFilter []RunHistoryRequestStatusFilterItem) {
	r.StatusFilter = statusFilter
	r.require(runHistoryRequestFieldStatusFilter)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryRequest) SetWorkflowID(workflowID *string) {
	r.WorkflowID = workflowID
	r.require(runHistoryRequestFieldWorkflowID)
}

func (r *RunHistoryRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RunHistoryRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RunHistoryRequest(body)
	return nil
}

func (r *RunHistoryRequest) MarshalJSON() ([]byte, error) {
	type embed RunHistoryRequest
	var marshaler = struct {
		embed
		EndDate   *internal.DateTime `json:"end_date"`
		StartDate *internal.DateTime `json:"start_date"`
	}{
		embed:     embed(*r),
		EndDate:   internal.NewDateTime(r.EndDate),
		StartDate: internal.NewDateTime(r.StartDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	runsStatsRequestFieldWorkflowID = big.NewInt(1 << 0)
)

type RunsStatsRequest struct {
	// workflow identifier
	WorkflowID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RunsStatsRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunsStatsRequest) SetWorkflowID(workflowID string) {
	r.WorkflowID = workflowID
	r.require(runsStatsRequestFieldWorkflowID)
}

// Per-run variable assignments and optional phone pin.
var (
	runConfigFieldPhoneID   = big.NewInt(1 << 0)
	runConfigFieldVariables = big.NewInt(1 << 1)
)

type RunConfig struct {
	// PhoneID pins this run to a specific phone (for dedicated phones).
	PhoneID *string `json:"phone_id,omitempty" url:"phone_id,omitempty"`
	// Array of variable maps keyed by node ID.
	Variables []map[string]any `json:"variables,omitempty" url:"variables,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RunConfig) GetPhoneID() *string {
	if r == nil {
		return nil
	}
	return r.PhoneID
}

func (r *RunConfig) GetVariables() []map[string]any {
	if r == nil {
		return nil
	}
	return r.Variables
}

func (r *RunConfig) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RunConfig) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetPhoneID sets the PhoneID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunConfig) SetPhoneID(phoneID *string) {
	r.PhoneID = phoneID
	r.require(runConfigFieldPhoneID)
}

// SetVariables sets the Variables field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunConfig) SetVariables(variables []map[string]any) {
	r.Variables = variables
	r.require(runConfigFieldVariables)
}

func (r *RunConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler RunConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RunConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunConfig) MarshalJSON() ([]byte, error) {
	type embed RunConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RunConfig) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Returned after successfully creating one or more runs.
var (
	runCreateResponseFieldSchema = big.NewInt(1 << 0)
	runCreateResponseFieldRunIDs = big.NewInt(1 << 1)
)

type RunCreateResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// List of created run identifiers.
	RunIDs []string `json:"run_ids,omitempty" url:"run_ids,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RunCreateResponse) GetSchema() *string {
	if r == nil {
		return nil
	}
	return r.Schema
}

func (r *RunCreateResponse) GetRunIDs() []string {
	if r == nil {
		return nil
	}
	return r.RunIDs
}

func (r *RunCreateResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RunCreateResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunCreateResponse) SetSchema(schema *string) {
	r.Schema = schema
	r.require(runCreateResponseFieldSchema)
}

// SetRunIDs sets the RunIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunCreateResponse) SetRunIDs(runIDs []string) {
	r.RunIDs = runIDs
	r.require(runCreateResponseFieldRunIDs)
}

func (r *RunCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RunCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RunCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunCreateResponse) MarshalJSON() ([]byte, error) {
	type embed RunCreateResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RunCreateResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// A single event recorded during a run.
var (
	runEventSummaryFieldBody      = big.NewInt(1 << 0)
	runEventSummaryFieldSessionID = big.NewInt(1 << 1)
	runEventSummaryFieldTimestamp = big.NewInt(1 << 2)
	runEventSummaryFieldType      = big.NewInt(1 << 3)
)

type RunEventSummary struct {
	// Event payload; shape depends on type.
	Body any `json:"body,omitempty" url:"body,omitempty"`
	// Session the event belongs to.
	SessionID string `json:"session_id" url:"session_id"`
	// When the event occurred.
	Timestamp time.Time `json:"timestamp" url:"timestamp"`
	// Event type (e.g. RUN_STARTED, OUTPUT_LOG).
	Type string `json:"type" url:"type"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RunEventSummary) GetBody() any {
	if r == nil {
		return nil
	}
	return r.Body
}

func (r *RunEventSummary) GetSessionID() string {
	if r == nil {
		return ""
	}
	return r.SessionID
}

func (r *RunEventSummary) GetTimestamp() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.Timestamp
}

func (r *RunEventSummary) GetType() string {
	if r == nil {
		return ""
	}
	return r.Type
}

func (r *RunEventSummary) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RunEventSummary) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetBody sets the Body field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventSummary) SetBody(body any) {
	r.Body = body
	r.require(runEventSummaryFieldBody)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventSummary) SetSessionID(sessionID string) {
	r.SessionID = sessionID
	r.require(runEventSummaryFieldSessionID)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventSummary) SetTimestamp(timestamp time.Time) {
	r.Timestamp = timestamp
	r.require(runEventSummaryFieldTimestamp)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventSummary) SetType(type_ string) {
	r.Type = type_
	r.require(runEventSummaryFieldType)
}

func (r *RunEventSummary) UnmarshalJSON(data []byte) error {
	type embed RunEventSummary
	var unmarshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RunEventSummary(unmarshaler.embed)
	r.Timestamp = unmarshaler.Timestamp.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunEventSummary) MarshalJSON() ([]byte, error) {
	type embed RunEventSummary
	var marshaler = struct {
		embed
		Timestamp *internal.DateTime `json:"timestamp"`
	}{
		embed:     embed(*r),
		Timestamp: internal.NewDateTime(r.Timestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RunEventSummary) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Paginated list of run events.
var (
	runEventsResponseFieldSchema           = big.NewInt(1 << 0)
	runEventsResponseFieldEvents           = big.NewInt(1 << 1)
	runEventsResponseFieldInferenceCosts   = big.NewInt(1 << 2)
	runEventsResponseFieldLimit            = big.NewInt(1 << 3)
	runEventsResponseFieldOffset           = big.NewInt(1 << 4)
	runEventsResponseFieldRetentionExpired = big.NewInt(1 << 5)
	runEventsResponseFieldSdkCallCosts     = big.NewInt(1 << 6)
	runEventsResponseFieldTotal            = big.NewInt(1 << 7)
)

type RunEventsResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Page of run event records.
	Events []*RunEventSummary `json:"events,omitempty" url:"events,omitempty"`
	// Billed microdollars per inference_id.
	InferenceCosts map[string]int64 `json:"inference_costs" url:"inference_costs"`
	// Page size used for this response.
	Limit int64 `json:"limit" url:"limit"`
	// Pagination offset used for this response.
	Offset int64 `json:"offset" url:"offset"`
	// True when the trace is past the plan's retention window; events are withheld.
	RetentionExpired bool `json:"retention_expired" url:"retention_expired"`
	// Billed microdollars per SDK-call span_id.
	SdkCallCosts map[string]int64 `json:"sdk_call_costs" url:"sdk_call_costs"`
	// Total number of events matching the query.
	Total int64 `json:"total" url:"total"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RunEventsResponse) GetSchema() *string {
	if r == nil {
		return nil
	}
	return r.Schema
}

func (r *RunEventsResponse) GetEvents() []*RunEventSummary {
	if r == nil {
		return nil
	}
	return r.Events
}

func (r *RunEventsResponse) GetInferenceCosts() map[string]int64 {
	if r == nil {
		return nil
	}
	return r.InferenceCosts
}

func (r *RunEventsResponse) GetLimit() int64 {
	if r == nil {
		return 0
	}
	return r.Limit
}

func (r *RunEventsResponse) GetOffset() int64 {
	if r == nil {
		return 0
	}
	return r.Offset
}

func (r *RunEventsResponse) GetRetentionExpired() bool {
	if r == nil {
		return false
	}
	return r.RetentionExpired
}

func (r *RunEventsResponse) GetSdkCallCosts() map[string]int64 {
	if r == nil {
		return nil
	}
	return r.SdkCallCosts
}

func (r *RunEventsResponse) GetTotal() int64 {
	if r == nil {
		return 0
	}
	return r.Total
}

func (r *RunEventsResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RunEventsResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventsResponse) SetSchema(schema *string) {
	r.Schema = schema
	r.require(runEventsResponseFieldSchema)
}

// SetEvents sets the Events field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventsResponse) SetEvents(events []*RunEventSummary) {
	r.Events = events
	r.require(runEventsResponseFieldEvents)
}

// SetInferenceCosts sets the InferenceCosts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventsResponse) SetInferenceCosts(inferenceCosts map[string]int64) {
	r.InferenceCosts = inferenceCosts
	r.require(runEventsResponseFieldInferenceCosts)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventsResponse) SetLimit(limit int64) {
	r.Limit = limit
	r.require(runEventsResponseFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventsResponse) SetOffset(offset int64) {
	r.Offset = offset
	r.require(runEventsResponseFieldOffset)
}

// SetRetentionExpired sets the RetentionExpired field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventsResponse) SetRetentionExpired(retentionExpired bool) {
	r.RetentionExpired = retentionExpired
	r.require(runEventsResponseFieldRetentionExpired)
}

// SetSdkCallCosts sets the SdkCallCosts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventsResponse) SetSdkCallCosts(sdkCallCosts map[string]int64) {
	r.SdkCallCosts = sdkCallCosts
	r.require(runEventsResponseFieldSdkCallCosts)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunEventsResponse) SetTotal(total int64) {
	r.Total = total
	r.require(runEventsResponseFieldTotal)
}

func (r *RunEventsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RunEventsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RunEventsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunEventsResponse) MarshalJSON() ([]byte, error) {
	type embed RunEventsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RunEventsResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// A single historic run record.
var (
	runHistoryItemFieldCanceledAt   = big.NewInt(1 << 0)
	runHistoryItemFieldCompletedAt  = big.NewInt(1 << 1)
	runHistoryItemFieldCreatedAt    = big.NewInt(1 << 2)
	runHistoryItemFieldErrorMessage = big.NewInt(1 << 3)
	runHistoryItemFieldOrgID        = big.NewInt(1 << 4)
	runHistoryItemFieldPhoneID      = big.NewInt(1 << 5)
	runHistoryItemFieldRunID        = big.NewInt(1 << 6)
	runHistoryItemFieldRunMetadata  = big.NewInt(1 << 7)
	runHistoryItemFieldStartedAt    = big.NewInt(1 << 8)
	runHistoryItemFieldStatus       = big.NewInt(1 << 9)
	runHistoryItemFieldSuccess      = big.NewInt(1 << 10)
	runHistoryItemFieldTrigger      = big.NewInt(1 << 11)
	runHistoryItemFieldUserID       = big.NewInt(1 << 12)
	runHistoryItemFieldVideoURL     = big.NewInt(1 << 13)
	runHistoryItemFieldWorkflowID   = big.NewInt(1 << 14)
)

type RunHistoryItem struct {
	// Run cancellation time in UTC.
	CanceledAt *time.Time `json:"canceled_at,omitempty" url:"canceled_at,omitempty"`
	// Run completion time in UTC.
	CompletedAt *time.Time `json:"completed_at,omitempty" url:"completed_at,omitempty"`
	// Run creation time in UTC.
	CreatedAt *time.Time `json:"created_at,omitempty" url:"created_at,omitempty"`
	// Error details if the run failed.
	ErrorMessage *string `json:"error_message,omitempty" url:"error_message,omitempty"`
	// Organization that owns the run.
	OrgID *string `json:"org_id,omitempty" url:"org_id,omitempty"`
	// Device that executed the run.
	PhoneID *string `json:"phone_id,omitempty" url:"phone_id,omitempty"`
	// Run identifier.
	RunID string `json:"run_id" url:"run_id"`
	// Serialized arbitrary metadata for the run.
	RunMetadata *string `json:"run_metadata,omitempty" url:"run_metadata,omitempty"`
	// Run start time in UTC.
	StartedAt *time.Time `json:"started_at,omitempty" url:"started_at,omitempty"`
	// Run's final status.
	Status RunHistoryItemStatus `json:"status" url:"status"`
	// Whether the run completed successfully.
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// Trigger identifies how the run was initiated.
	Trigger RunHistoryItemTrigger `json:"trigger" url:"trigger"`
	// User who initiated the run.
	UserID string `json:"user_id" url:"user_id"`
	// URL for the run recording video.
	VideoURL *string `json:"video_url,omitempty" url:"video_url,omitempty"`
	// Associated workflow identifier.
	WorkflowID string `json:"workflow_id" url:"workflow_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RunHistoryItem) GetCanceledAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CanceledAt
}

func (r *RunHistoryItem) GetCompletedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CompletedAt
}

func (r *RunHistoryItem) GetCreatedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *RunHistoryItem) GetErrorMessage() *string {
	if r == nil {
		return nil
	}
	return r.ErrorMessage
}

func (r *RunHistoryItem) GetOrgID() *string {
	if r == nil {
		return nil
	}
	return r.OrgID
}

func (r *RunHistoryItem) GetPhoneID() *string {
	if r == nil {
		return nil
	}
	return r.PhoneID
}

func (r *RunHistoryItem) GetRunID() string {
	if r == nil {
		return ""
	}
	return r.RunID
}

func (r *RunHistoryItem) GetRunMetadata() *string {
	if r == nil {
		return nil
	}
	return r.RunMetadata
}

func (r *RunHistoryItem) GetStartedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.StartedAt
}

func (r *RunHistoryItem) GetStatus() RunHistoryItemStatus {
	if r == nil {
		return ""
	}
	return r.Status
}

func (r *RunHistoryItem) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *RunHistoryItem) GetTrigger() RunHistoryItemTrigger {
	if r == nil {
		return ""
	}
	return r.Trigger
}

func (r *RunHistoryItem) GetUserID() string {
	if r == nil {
		return ""
	}
	return r.UserID
}

func (r *RunHistoryItem) GetVideoURL() *string {
	if r == nil {
		return nil
	}
	return r.VideoURL
}

func (r *RunHistoryItem) GetWorkflowID() string {
	if r == nil {
		return ""
	}
	return r.WorkflowID
}

func (r *RunHistoryItem) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RunHistoryItem) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCanceledAt sets the CanceledAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetCanceledAt(canceledAt *time.Time) {
	r.CanceledAt = canceledAt
	r.require(runHistoryItemFieldCanceledAt)
}

// SetCompletedAt sets the CompletedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetCompletedAt(completedAt *time.Time) {
	r.CompletedAt = completedAt
	r.require(runHistoryItemFieldCompletedAt)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetCreatedAt(createdAt *time.Time) {
	r.CreatedAt = createdAt
	r.require(runHistoryItemFieldCreatedAt)
}

// SetErrorMessage sets the ErrorMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetErrorMessage(errorMessage *string) {
	r.ErrorMessage = errorMessage
	r.require(runHistoryItemFieldErrorMessage)
}

// SetOrgID sets the OrgID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetOrgID(orgID *string) {
	r.OrgID = orgID
	r.require(runHistoryItemFieldOrgID)
}

// SetPhoneID sets the PhoneID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetPhoneID(phoneID *string) {
	r.PhoneID = phoneID
	r.require(runHistoryItemFieldPhoneID)
}

// SetRunID sets the RunID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetRunID(runID string) {
	r.RunID = runID
	r.require(runHistoryItemFieldRunID)
}

// SetRunMetadata sets the RunMetadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetRunMetadata(runMetadata *string) {
	r.RunMetadata = runMetadata
	r.require(runHistoryItemFieldRunMetadata)
}

// SetStartedAt sets the StartedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetStartedAt(startedAt *time.Time) {
	r.StartedAt = startedAt
	r.require(runHistoryItemFieldStartedAt)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetStatus(status RunHistoryItemStatus) {
	r.Status = status
	r.require(runHistoryItemFieldStatus)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetSuccess(success *bool) {
	r.Success = success
	r.require(runHistoryItemFieldSuccess)
}

// SetTrigger sets the Trigger field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetTrigger(trigger RunHistoryItemTrigger) {
	r.Trigger = trigger
	r.require(runHistoryItemFieldTrigger)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetUserID(userID string) {
	r.UserID = userID
	r.require(runHistoryItemFieldUserID)
}

// SetVideoURL sets the VideoURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetVideoURL(videoURL *string) {
	r.VideoURL = videoURL
	r.require(runHistoryItemFieldVideoURL)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryItem) SetWorkflowID(workflowID string) {
	r.WorkflowID = workflowID
	r.require(runHistoryItemFieldWorkflowID)
}

func (r *RunHistoryItem) UnmarshalJSON(data []byte) error {
	type embed RunHistoryItem
	var unmarshaler = struct {
		embed
		CanceledAt  *internal.DateTime `json:"canceled_at,omitempty"`
		CompletedAt *internal.DateTime `json:"completed_at,omitempty"`
		CreatedAt   *internal.DateTime `json:"created_at,omitempty"`
		StartedAt   *internal.DateTime `json:"started_at,omitempty"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RunHistoryItem(unmarshaler.embed)
	r.CanceledAt = unmarshaler.CanceledAt.TimePtr()
	r.CompletedAt = unmarshaler.CompletedAt.TimePtr()
	r.CreatedAt = unmarshaler.CreatedAt.TimePtr()
	r.StartedAt = unmarshaler.StartedAt.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunHistoryItem) MarshalJSON() ([]byte, error) {
	type embed RunHistoryItem
	var marshaler = struct {
		embed
		CanceledAt  *internal.DateTime `json:"canceled_at,omitempty"`
		CompletedAt *internal.DateTime `json:"completed_at,omitempty"`
		CreatedAt   *internal.DateTime `json:"created_at,omitempty"`
		StartedAt   *internal.DateTime `json:"started_at,omitempty"`
	}{
		embed:       embed(*r),
		CanceledAt:  internal.NewOptionalDateTime(r.CanceledAt),
		CompletedAt: internal.NewOptionalDateTime(r.CompletedAt),
		CreatedAt:   internal.NewOptionalDateTime(r.CreatedAt),
		StartedAt:   internal.NewOptionalDateTime(r.StartedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RunHistoryItem) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Run's final status.
type RunHistoryItemStatus string

const (
	RunHistoryItemStatusQueued    RunHistoryItemStatus = "queued"
	RunHistoryItemStatusRunning   RunHistoryItemStatus = "running"
	RunHistoryItemStatusCompleted RunHistoryItemStatus = "completed"
	RunHistoryItemStatusFailed    RunHistoryItemStatus = "failed"
	RunHistoryItemStatusCancelled RunHistoryItemStatus = "cancelled"
)

func NewRunHistoryItemStatusFromString(s string) (RunHistoryItemStatus, error) {
	switch s {
	case "queued":
		return RunHistoryItemStatusQueued, nil
	case "running":
		return RunHistoryItemStatusRunning, nil
	case "completed":
		return RunHistoryItemStatusCompleted, nil
	case "failed":
		return RunHistoryItemStatusFailed, nil
	case "cancelled":
		return RunHistoryItemStatusCancelled, nil
	}
	var t RunHistoryItemStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RunHistoryItemStatus) Ptr() *RunHistoryItemStatus {
	return &r
}

// Trigger identifies how the run was initiated.
type RunHistoryItemTrigger string

const (
	RunHistoryItemTriggerManual    RunHistoryItemTrigger = "manual"
	RunHistoryItemTriggerScheduled RunHistoryItemTrigger = "scheduled"
	RunHistoryItemTriggerAPI       RunHistoryItemTrigger = "api"
)

func NewRunHistoryItemTriggerFromString(s string) (RunHistoryItemTrigger, error) {
	switch s {
	case "manual":
		return RunHistoryItemTriggerManual, nil
	case "scheduled":
		return RunHistoryItemTriggerScheduled, nil
	case "api":
		return RunHistoryItemTriggerAPI, nil
	}
	var t RunHistoryItemTrigger
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RunHistoryItemTrigger) Ptr() *RunHistoryItemTrigger {
	return &r
}

// Paginated list of historic runs.
var (
	runHistoryResponseFieldSchema = big.NewInt(1 << 0)
	runHistoryResponseFieldLimit  = big.NewInt(1 << 1)
	runHistoryResponseFieldOffset = big.NewInt(1 << 2)
	runHistoryResponseFieldRuns   = big.NewInt(1 << 3)
	runHistoryResponseFieldTotal  = big.NewInt(1 << 4)
)

type RunHistoryResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Page size used for this response.
	Limit int64 `json:"limit" url:"limit"`
	// Pagination offset used for this response.
	Offset int64 `json:"offset" url:"offset"`
	// Page of historic run records.
	Runs []*RunHistoryItem `json:"runs,omitempty" url:"runs,omitempty"`
	// Total number of runs matching the query.
	Total int64 `json:"total" url:"total"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RunHistoryResponse) GetSchema() *string {
	if r == nil {
		return nil
	}
	return r.Schema
}

func (r *RunHistoryResponse) GetLimit() int64 {
	if r == nil {
		return 0
	}
	return r.Limit
}

func (r *RunHistoryResponse) GetOffset() int64 {
	if r == nil {
		return 0
	}
	return r.Offset
}

func (r *RunHistoryResponse) GetRuns() []*RunHistoryItem {
	if r == nil {
		return nil
	}
	return r.Runs
}

func (r *RunHistoryResponse) GetTotal() int64 {
	if r == nil {
		return 0
	}
	return r.Total
}

func (r *RunHistoryResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RunHistoryResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryResponse) SetSchema(schema *string) {
	r.Schema = schema
	r.require(runHistoryResponseFieldSchema)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryResponse) SetLimit(limit int64) {
	r.Limit = limit
	r.require(runHistoryResponseFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryResponse) SetOffset(offset int64) {
	r.Offset = offset
	r.require(runHistoryResponseFieldOffset)
}

// SetRuns sets the Runs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryResponse) SetRuns(runs []*RunHistoryItem) {
	r.Runs = runs
	r.require(runHistoryResponseFieldRuns)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunHistoryResponse) SetTotal(total int64) {
	r.Total = total
	r.require(runHistoryResponseFieldTotal)
}

func (r *RunHistoryResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RunHistoryResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RunHistoryResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunHistoryResponse) MarshalJSON() ([]byte, error) {
	type embed RunHistoryResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RunHistoryResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Paginated list of runs.
var (
	runListResponseFieldSchema = big.NewInt(1 << 0)
	runListResponseFieldLimit  = big.NewInt(1 << 1)
	runListResponseFieldOffset = big.NewInt(1 << 2)
	runListResponseFieldRuns   = big.NewInt(1 << 3)
	runListResponseFieldTotal  = big.NewInt(1 << 4)
)

type RunListResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Page size used for this response.
	Limit int64 `json:"limit" url:"limit"`
	// Pagination offset used for this response.
	Offset int64 `json:"offset" url:"offset"`
	// Page of run records.
	Runs []*RunResponse `json:"runs,omitempty" url:"runs,omitempty"`
	// Total number of runs matching the query.
	Total int64 `json:"total" url:"total"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RunListResponse) GetSchema() *string {
	if r == nil {
		return nil
	}
	return r.Schema
}

func (r *RunListResponse) GetLimit() int64 {
	if r == nil {
		return 0
	}
	return r.Limit
}

func (r *RunListResponse) GetOffset() int64 {
	if r == nil {
		return 0
	}
	return r.Offset
}

func (r *RunListResponse) GetRuns() []*RunResponse {
	if r == nil {
		return nil
	}
	return r.Runs
}

func (r *RunListResponse) GetTotal() int64 {
	if r == nil {
		return 0
	}
	return r.Total
}

func (r *RunListResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RunListResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunListResponse) SetSchema(schema *string) {
	r.Schema = schema
	r.require(runListResponseFieldSchema)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunListResponse) SetLimit(limit int64) {
	r.Limit = limit
	r.require(runListResponseFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunListResponse) SetOffset(offset int64) {
	r.Offset = offset
	r.require(runListResponseFieldOffset)
}

// SetRuns sets the Runs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunListResponse) SetRuns(runs []*RunResponse) {
	r.Runs = runs
	r.require(runListResponseFieldRuns)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunListResponse) SetTotal(total int64) {
	r.Total = total
	r.require(runListResponseFieldTotal)
}

func (r *RunListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RunListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RunListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunListResponse) MarshalJSON() ([]byte, error) {
	type embed RunListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RunListResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Full run record returned by run endpoints.
var (
	runResponseFieldSchema              = big.NewInt(1 << 0)
	runResponseFieldCanceledAt          = big.NewInt(1 << 1)
	runResponseFieldCompletedAt         = big.NewInt(1 << 2)
	runResponseFieldCreatedAt           = big.NewInt(1 << 3)
	runResponseFieldErrorMessage        = big.NewInt(1 << 4)
	runResponseFieldID                  = big.NewInt(1 << 5)
	runResponseFieldLogs                = big.NewInt(1 << 6)
	runResponseFieldPhoneID             = big.NewInt(1 << 7)
	runResponseFieldRunMetadata         = big.NewInt(1 << 8)
	runResponseFieldSessionID           = big.NewInt(1 << 9)
	runResponseFieldStartTimeoutSeconds = big.NewInt(1 << 10)
	runResponseFieldStartedAt           = big.NewInt(1 << 11)
	runResponseFieldStatus              = big.NewInt(1 << 12)
	runResponseFieldSuccess             = big.NewInt(1 << 13)
	runResponseFieldTraceExpiredAt      = big.NewInt(1 << 14)
	runResponseFieldTrigger             = big.NewInt(1 << 15)
	runResponseFieldUpdatedAt           = big.NewInt(1 << 16)
	runResponseFieldUserID              = big.NewInt(1 << 17)
	runResponseFieldVariables           = big.NewInt(1 << 18)
	runResponseFieldVideoURL            = big.NewInt(1 << 19)
	runResponseFieldWorkflowID          = big.NewInt(1 << 20)
)

type RunResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Timestamp when the run was cancelled.
	CanceledAt *time.Time `json:"canceled_at,omitempty" url:"canceled_at,omitempty"`
	// Timestamp when the run finished.
	CompletedAt *time.Time `json:"completed_at,omitempty" url:"completed_at,omitempty"`
	// Timestamp when the run record was created.
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// Error details if the run failed.
	ErrorMessage *string `json:"error_message,omitempty" url:"error_message,omitempty"`
	// Run identifier.
	ID string `json:"id" url:"id"`
	// Run's execution log output.
	Logs *string `json:"logs,omitempty" url:"logs,omitempty"`
	// Device executing the run.
	PhoneID *string `json:"phone_id,omitempty" url:"phone_id,omitempty"`
	// Arbitrary metadata attached to the run.
	RunMetadata map[string]any `json:"run_metadata,omitempty" url:"run_metadata,omitempty"`
	// Session associated with this run.
	SessionID *string `json:"session_id,omitempty" url:"session_id,omitempty"`
	// How long the queued run may wait for a phone before auto-cancel.
	StartTimeoutSeconds *int64 `json:"start_timeout_seconds,omitempty" url:"start_timeout_seconds,omitempty"`
	// Timestamp when the run began executing.
	StartedAt *time.Time `json:"started_at,omitempty" url:"started_at,omitempty"`
	// Current lifecycle state of the run.
	Status RunResponseStatus `json:"status" url:"status"`
	// Whether the run completed without error.
	Success *bool `json:"success,omitempty" url:"success,omitempty"`
	// When the trace recording was deleted.
	TraceExpiredAt *time.Time `json:"trace_expired_at,omitempty" url:"trace_expired_at,omitempty"`
	// Trigger identifies how the run was initiated.
	Trigger RunResponseTrigger `json:"trigger" url:"trigger"`
	// Timestamp of the last update to the run record.
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`
	// User who initiated the run.
	UserID string `json:"user_id" url:"user_id"`
	// Variable configuration used for the run.
	Variables map[string]any `json:"variables,omitempty" url:"variables,omitempty"`
	// URL for the run recording video.
	VideoURL *string `json:"video_url,omitempty" url:"video_url,omitempty"`
	// Workflow this run belongs to.
	WorkflowID string `json:"workflow_id" url:"workflow_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RunResponse) GetSchema() *string {
	if r == nil {
		return nil
	}
	return r.Schema
}

func (r *RunResponse) GetCanceledAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CanceledAt
}

func (r *RunResponse) GetCompletedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.CompletedAt
}

func (r *RunResponse) GetCreatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.CreatedAt
}

func (r *RunResponse) GetErrorMessage() *string {
	if r == nil {
		return nil
	}
	return r.ErrorMessage
}

func (r *RunResponse) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RunResponse) GetLogs() *string {
	if r == nil {
		return nil
	}
	return r.Logs
}

func (r *RunResponse) GetPhoneID() *string {
	if r == nil {
		return nil
	}
	return r.PhoneID
}

func (r *RunResponse) GetRunMetadata() map[string]any {
	if r == nil {
		return nil
	}
	return r.RunMetadata
}

func (r *RunResponse) GetSessionID() *string {
	if r == nil {
		return nil
	}
	return r.SessionID
}

func (r *RunResponse) GetStartTimeoutSeconds() *int64 {
	if r == nil {
		return nil
	}
	return r.StartTimeoutSeconds
}

func (r *RunResponse) GetStartedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.StartedAt
}

func (r *RunResponse) GetStatus() RunResponseStatus {
	if r == nil {
		return ""
	}
	return r.Status
}

func (r *RunResponse) GetSuccess() *bool {
	if r == nil {
		return nil
	}
	return r.Success
}

func (r *RunResponse) GetTraceExpiredAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.TraceExpiredAt
}

func (r *RunResponse) GetTrigger() RunResponseTrigger {
	if r == nil {
		return ""
	}
	return r.Trigger
}

func (r *RunResponse) GetUpdatedAt() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.UpdatedAt
}

func (r *RunResponse) GetUserID() string {
	if r == nil {
		return ""
	}
	return r.UserID
}

func (r *RunResponse) GetVariables() map[string]any {
	if r == nil {
		return nil
	}
	return r.Variables
}

func (r *RunResponse) GetVideoURL() *string {
	if r == nil {
		return nil
	}
	return r.VideoURL
}

func (r *RunResponse) GetWorkflowID() string {
	if r == nil {
		return ""
	}
	return r.WorkflowID
}

func (r *RunResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RunResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetSchema(schema *string) {
	r.Schema = schema
	r.require(runResponseFieldSchema)
}

// SetCanceledAt sets the CanceledAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetCanceledAt(canceledAt *time.Time) {
	r.CanceledAt = canceledAt
	r.require(runResponseFieldCanceledAt)
}

// SetCompletedAt sets the CompletedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetCompletedAt(completedAt *time.Time) {
	r.CompletedAt = completedAt
	r.require(runResponseFieldCompletedAt)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetCreatedAt(createdAt time.Time) {
	r.CreatedAt = createdAt
	r.require(runResponseFieldCreatedAt)
}

// SetErrorMessage sets the ErrorMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetErrorMessage(errorMessage *string) {
	r.ErrorMessage = errorMessage
	r.require(runResponseFieldErrorMessage)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetID(id string) {
	r.ID = id
	r.require(runResponseFieldID)
}

// SetLogs sets the Logs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetLogs(logs *string) {
	r.Logs = logs
	r.require(runResponseFieldLogs)
}

// SetPhoneID sets the PhoneID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetPhoneID(phoneID *string) {
	r.PhoneID = phoneID
	r.require(runResponseFieldPhoneID)
}

// SetRunMetadata sets the RunMetadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetRunMetadata(runMetadata map[string]any) {
	r.RunMetadata = runMetadata
	r.require(runResponseFieldRunMetadata)
}

// SetSessionID sets the SessionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetSessionID(sessionID *string) {
	r.SessionID = sessionID
	r.require(runResponseFieldSessionID)
}

// SetStartTimeoutSeconds sets the StartTimeoutSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetStartTimeoutSeconds(startTimeoutSeconds *int64) {
	r.StartTimeoutSeconds = startTimeoutSeconds
	r.require(runResponseFieldStartTimeoutSeconds)
}

// SetStartedAt sets the StartedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetStartedAt(startedAt *time.Time) {
	r.StartedAt = startedAt
	r.require(runResponseFieldStartedAt)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetStatus(status RunResponseStatus) {
	r.Status = status
	r.require(runResponseFieldStatus)
}

// SetSuccess sets the Success field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetSuccess(success *bool) {
	r.Success = success
	r.require(runResponseFieldSuccess)
}

// SetTraceExpiredAt sets the TraceExpiredAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetTraceExpiredAt(traceExpiredAt *time.Time) {
	r.TraceExpiredAt = traceExpiredAt
	r.require(runResponseFieldTraceExpiredAt)
}

// SetTrigger sets the Trigger field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetTrigger(trigger RunResponseTrigger) {
	r.Trigger = trigger
	r.require(runResponseFieldTrigger)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetUpdatedAt(updatedAt time.Time) {
	r.UpdatedAt = updatedAt
	r.require(runResponseFieldUpdatedAt)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetUserID(userID string) {
	r.UserID = userID
	r.require(runResponseFieldUserID)
}

// SetVariables sets the Variables field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetVariables(variables map[string]any) {
	r.Variables = variables
	r.require(runResponseFieldVariables)
}

// SetVideoURL sets the VideoURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetVideoURL(videoURL *string) {
	r.VideoURL = videoURL
	r.require(runResponseFieldVideoURL)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunResponse) SetWorkflowID(workflowID string) {
	r.WorkflowID = workflowID
	r.require(runResponseFieldWorkflowID)
}

func (r *RunResponse) UnmarshalJSON(data []byte) error {
	type embed RunResponse
	var unmarshaler = struct {
		embed
		CanceledAt     *internal.DateTime `json:"canceled_at,omitempty"`
		CompletedAt    *internal.DateTime `json:"completed_at,omitempty"`
		CreatedAt      *internal.DateTime `json:"created_at"`
		StartedAt      *internal.DateTime `json:"started_at,omitempty"`
		TraceExpiredAt *internal.DateTime `json:"trace_expired_at,omitempty"`
		UpdatedAt      *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*r),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*r = RunResponse(unmarshaler.embed)
	r.CanceledAt = unmarshaler.CanceledAt.TimePtr()
	r.CompletedAt = unmarshaler.CompletedAt.TimePtr()
	r.CreatedAt = unmarshaler.CreatedAt.Time()
	r.StartedAt = unmarshaler.StartedAt.TimePtr()
	r.TraceExpiredAt = unmarshaler.TraceExpiredAt.TimePtr()
	r.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunResponse) MarshalJSON() ([]byte, error) {
	type embed RunResponse
	var marshaler = struct {
		embed
		CanceledAt     *internal.DateTime `json:"canceled_at,omitempty"`
		CompletedAt    *internal.DateTime `json:"completed_at,omitempty"`
		CreatedAt      *internal.DateTime `json:"created_at"`
		StartedAt      *internal.DateTime `json:"started_at,omitempty"`
		TraceExpiredAt *internal.DateTime `json:"trace_expired_at,omitempty"`
		UpdatedAt      *internal.DateTime `json:"updated_at"`
	}{
		embed:          embed(*r),
		CanceledAt:     internal.NewOptionalDateTime(r.CanceledAt),
		CompletedAt:    internal.NewOptionalDateTime(r.CompletedAt),
		CreatedAt:      internal.NewDateTime(r.CreatedAt),
		StartedAt:      internal.NewOptionalDateTime(r.StartedAt),
		TraceExpiredAt: internal.NewOptionalDateTime(r.TraceExpiredAt),
		UpdatedAt:      internal.NewDateTime(r.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RunResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Current lifecycle state of the run.
type RunResponseStatus string

const (
	RunResponseStatusQueued    RunResponseStatus = "queued"
	RunResponseStatusRunning   RunResponseStatus = "running"
	RunResponseStatusCompleted RunResponseStatus = "completed"
	RunResponseStatusFailed    RunResponseStatus = "failed"
	RunResponseStatusCancelled RunResponseStatus = "cancelled"
)

func NewRunResponseStatusFromString(s string) (RunResponseStatus, error) {
	switch s {
	case "queued":
		return RunResponseStatusQueued, nil
	case "running":
		return RunResponseStatusRunning, nil
	case "completed":
		return RunResponseStatusCompleted, nil
	case "failed":
		return RunResponseStatusFailed, nil
	case "cancelled":
		return RunResponseStatusCancelled, nil
	}
	var t RunResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RunResponseStatus) Ptr() *RunResponseStatus {
	return &r
}

// Trigger identifies how the run was initiated.
type RunResponseTrigger string

const (
	RunResponseTriggerManual    RunResponseTrigger = "manual"
	RunResponseTriggerScheduled RunResponseTrigger = "scheduled"
	RunResponseTriggerAPI       RunResponseTrigger = "api"
)

func NewRunResponseTriggerFromString(s string) (RunResponseTrigger, error) {
	switch s {
	case "manual":
		return RunResponseTriggerManual, nil
	case "scheduled":
		return RunResponseTriggerScheduled, nil
	case "api":
		return RunResponseTriggerAPI, nil
	}
	var t RunResponseTrigger
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RunResponseTrigger) Ptr() *RunResponseTrigger {
	return &r
}

// A single sort column and direction for run list queries.
var (
	runSortSpecFieldField = big.NewInt(1 << 0)
	runSortSpecFieldOrder = big.NewInt(1 << 1)
)

type RunSortSpec struct {
	// Column to sort by.
	Field string `json:"field" url:"field"`
	// Sort direction.
	Order string `json:"order" url:"order"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RunSortSpec) GetField() string {
	if r == nil {
		return ""
	}
	return r.Field
}

func (r *RunSortSpec) GetOrder() string {
	if r == nil {
		return ""
	}
	return r.Order
}

func (r *RunSortSpec) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RunSortSpec) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetField sets the Field field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunSortSpec) SetField(field string) {
	r.Field = field
	r.require(runSortSpecFieldField)
}

// SetOrder sets the Order field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunSortSpec) SetOrder(order string) {
	r.Order = order
	r.require(runSortSpecFieldOrder)
}

func (r *RunSortSpec) UnmarshalJSON(data []byte) error {
	type unmarshaler RunSortSpec
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RunSortSpec(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunSortSpec) MarshalJSON() ([]byte, error) {
	type embed RunSortSpec
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RunSortSpec) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// RunStatsResponse summarizes run statistics for a workflow or organization.
var (
	runStatsResponseFieldSchema      = big.NewInt(1 << 0)
	runStatsResponseFieldSuccessRate = big.NewInt(1 << 1)
	runStatsResponseFieldTotalRuns   = big.NewInt(1 << 2)
)

type RunStatsResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Fraction of completed+failed runs that succeeded, from 0.0 to 1.0 (multiply by 100 for a percentage). Note: total_runs counts all states, so it is a larger population than this rate's denominator.
	SuccessRate float64 `json:"success_rate" url:"success_rate"`
	// Total number of runs.
	TotalRuns int64 `json:"total_runs" url:"total_runs"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RunStatsResponse) GetSchema() *string {
	if r == nil {
		return nil
	}
	return r.Schema
}

func (r *RunStatsResponse) GetSuccessRate() float64 {
	if r == nil {
		return 0
	}
	return r.SuccessRate
}

func (r *RunStatsResponse) GetTotalRuns() int64 {
	if r == nil {
		return 0
	}
	return r.TotalRuns
}

func (r *RunStatsResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RunStatsResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunStatsResponse) SetSchema(schema *string) {
	r.Schema = schema
	r.require(runStatsResponseFieldSchema)
}

// SetSuccessRate sets the SuccessRate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunStatsResponse) SetSuccessRate(successRate float64) {
	r.SuccessRate = successRate
	r.require(runStatsResponseFieldSuccessRate)
}

// SetTotalRuns sets the TotalRuns field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunStatsResponse) SetTotalRuns(totalRuns int64) {
	r.TotalRuns = totalRuns
	r.require(runStatsResponseFieldTotalRuns)
}

func (r *RunStatsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RunStatsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RunStatsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunStatsResponse) MarshalJSON() ([]byte, error) {
	type embed RunStatsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RunStatsResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Generic success message returned by run mutation endpoints.
var (
	runSuccessResponseFieldSchema  = big.NewInt(1 << 0)
	runSuccessResponseFieldMessage = big.NewInt(1 << 1)
)

type RunSuccessResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Human-readable result description.
	Message string `json:"message" url:"message"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RunSuccessResponse) GetSchema() *string {
	if r == nil {
		return nil
	}
	return r.Schema
}

func (r *RunSuccessResponse) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *RunSuccessResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RunSuccessResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunSuccessResponse) SetSchema(schema *string) {
	r.Schema = schema
	r.require(runSuccessResponseFieldSchema)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RunSuccessResponse) SetMessage(message string) {
	r.Message = message
	r.require(runSuccessResponseFieldMessage)
}

func (r *RunSuccessResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RunSuccessResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RunSuccessResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RunSuccessResponse) MarshalJSON() ([]byte, error) {
	type embed RunSuccessResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RunSuccessResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RunHistoryRequestStatusFilterItem string

const (
	RunHistoryRequestStatusFilterItemQueued    RunHistoryRequestStatusFilterItem = "queued"
	RunHistoryRequestStatusFilterItemRunning   RunHistoryRequestStatusFilterItem = "running"
	RunHistoryRequestStatusFilterItemCompleted RunHistoryRequestStatusFilterItem = "completed"
	RunHistoryRequestStatusFilterItemFailed    RunHistoryRequestStatusFilterItem = "failed"
	RunHistoryRequestStatusFilterItemCancelled RunHistoryRequestStatusFilterItem = "cancelled"
)

func NewRunHistoryRequestStatusFilterItemFromString(s string) (RunHistoryRequestStatusFilterItem, error) {
	switch s {
	case "queued":
		return RunHistoryRequestStatusFilterItemQueued, nil
	case "running":
		return RunHistoryRequestStatusFilterItemRunning, nil
	case "completed":
		return RunHistoryRequestStatusFilterItemCompleted, nil
	case "failed":
		return RunHistoryRequestStatusFilterItemFailed, nil
	case "cancelled":
		return RunHistoryRequestStatusFilterItemCancelled, nil
	}
	var t RunHistoryRequestStatusFilterItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RunHistoryRequestStatusFilterItem) Ptr() *RunHistoryRequestStatusFilterItem {
	return &r
}

type RunListRequestStatusFilterItem string

const (
	RunListRequestStatusFilterItemQueued    RunListRequestStatusFilterItem = "queued"
	RunListRequestStatusFilterItemRunning   RunListRequestStatusFilterItem = "running"
	RunListRequestStatusFilterItemCompleted RunListRequestStatusFilterItem = "completed"
	RunListRequestStatusFilterItemFailed    RunListRequestStatusFilterItem = "failed"
	RunListRequestStatusFilterItemCancelled RunListRequestStatusFilterItem = "cancelled"
)

func NewRunListRequestStatusFilterItemFromString(s string) (RunListRequestStatusFilterItem, error) {
	switch s {
	case "queued":
		return RunListRequestStatusFilterItemQueued, nil
	case "running":
		return RunListRequestStatusFilterItemRunning, nil
	case "completed":
		return RunListRequestStatusFilterItemCompleted, nil
	case "failed":
		return RunListRequestStatusFilterItemFailed, nil
	case "cancelled":
		return RunListRequestStatusFilterItemCancelled, nil
	}
	var t RunListRequestStatusFilterItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RunListRequestStatusFilterItem) Ptr() *RunListRequestStatusFilterItem {
	return &r
}

type RunListRequestTriggerFilterItem string

const (
	RunListRequestTriggerFilterItemManual    RunListRequestTriggerFilterItem = "manual"
	RunListRequestTriggerFilterItemScheduled RunListRequestTriggerFilterItem = "scheduled"
	RunListRequestTriggerFilterItemAPI       RunListRequestTriggerFilterItem = "api"
)

func NewRunListRequestTriggerFilterItemFromString(s string) (RunListRequestTriggerFilterItem, error) {
	switch s {
	case "manual":
		return RunListRequestTriggerFilterItemManual, nil
	case "scheduled":
		return RunListRequestTriggerFilterItemScheduled, nil
	case "api":
		return RunListRequestTriggerFilterItemAPI, nil
	}
	var t RunListRequestTriggerFilterItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RunListRequestTriggerFilterItem) Ptr() *RunListRequestTriggerFilterItem {
	return &r
}
