// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/axilioai/platform-go/internal"
	big "math/big"
	time "time"
)

var (
	workflowCreateRequestFieldCode      = big.NewInt(1 << 0)
	workflowCreateRequestFieldName      = big.NewInt(1 << 1)
	workflowCreateRequestFieldOcrEngine = big.NewInt(1 << 2)
	workflowCreateRequestFieldPlatform  = big.NewInt(1 << 3)
)

type WorkflowCreateRequest struct {
	// Optional Python source for the workflow's first revision, saved atomically with the workflow when provided.
	Code *string `json:"code,omitempty" url:"-"`
	// Human-readable workflow name.
	Name string `json:"name" url:"-"`
	// OCR backend to use.
	OcrEngine *WorkflowCreateRequestOcrEngine `json:"ocr_engine,omitempty" url:"-"`
	// Target OS platform.
	Platform *WorkflowCreateRequestPlatform `json:"platform,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowCreateRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowCreateRequest) SetCode(code *string) {
	w.Code = code
	w.require(workflowCreateRequestFieldCode)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowCreateRequest) SetName(name string) {
	w.Name = name
	w.require(workflowCreateRequestFieldName)
}

// SetOcrEngine sets the OcrEngine field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowCreateRequest) SetOcrEngine(ocrEngine *WorkflowCreateRequestOcrEngine) {
	w.OcrEngine = ocrEngine
	w.require(workflowCreateRequestFieldOcrEngine)
}

// SetPlatform sets the Platform field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowCreateRequest) SetPlatform(platform *WorkflowCreateRequestPlatform) {
	w.Platform = platform
	w.require(workflowCreateRequestFieldPlatform)
}

func (w *WorkflowCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*w = WorkflowCreateRequest(body)
	return nil
}

func (w *WorkflowCreateRequest) MarshalJSON() ([]byte, error) {
	type embed WorkflowCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	workflowsDeleteRequestFieldWorkflowID = big.NewInt(1 << 0)
)

type WorkflowsDeleteRequest struct {
	// workflow identifier
	WorkflowID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowsDeleteRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsDeleteRequest) SetWorkflowID(workflowID string) {
	w.WorkflowID = workflowID
	w.require(workflowsDeleteRequestFieldWorkflowID)
}

var (
	workflowsGetRequestFieldWorkflowID = big.NewInt(1 << 0)
)

type WorkflowsGetRequest struct {
	// workflow identifier
	WorkflowID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowsGetRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsGetRequest) SetWorkflowID(workflowID string) {
	w.WorkflowID = workflowID
	w.require(workflowsGetRequestFieldWorkflowID)
}

var (
	workflowsGetCodeRequestFieldWorkflowID = big.NewInt(1 << 0)
)

type WorkflowsGetCodeRequest struct {
	// workflow identifier
	WorkflowID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowsGetCodeRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsGetCodeRequest) SetWorkflowID(workflowID string) {
	w.WorkflowID = workflowID
	w.require(workflowsGetCodeRequestFieldWorkflowID)
}

var (
	workflowsGetRevisionRequestFieldWorkflowID = big.NewInt(1 << 0)
	workflowsGetRevisionRequestFieldRevisionID = big.NewInt(1 << 1)
)

type WorkflowsGetRevisionRequest struct {
	// workflow identifier
	WorkflowID string `json:"-" url:"-"`
	// revision identifier
	RevisionID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowsGetRevisionRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsGetRevisionRequest) SetWorkflowID(workflowID string) {
	w.WorkflowID = workflowID
	w.require(workflowsGetRevisionRequestFieldWorkflowID)
}

// SetRevisionID sets the RevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsGetRevisionRequest) SetRevisionID(revisionID string) {
	w.RevisionID = revisionID
	w.require(workflowsGetRevisionRequestFieldRevisionID)
}

var (
	workflowsListRequestFieldLimit         = big.NewInt(1 << 0)
	workflowsListRequestFieldOffset        = big.NewInt(1 << 1)
	workflowsListRequestFieldSearch        = big.NewInt(1 << 2)
	workflowsListRequestFieldStatus        = big.NewInt(1 << 3)
	workflowsListRequestFieldPlatform      = big.NewInt(1 << 4)
	workflowsListRequestFieldCreatedAfter  = big.NewInt(1 << 5)
	workflowsListRequestFieldCreatedBefore = big.NewInt(1 << 6)
	workflowsListRequestFieldLastRunAfter  = big.NewInt(1 << 7)
	workflowsListRequestFieldLastRunBefore = big.NewInt(1 << 8)
)

type WorkflowsListRequest struct {
	Limit  *int64 `json:"-" url:"limit,omitempty"`
	Offset *int64 `json:"-" url:"offset,omitempty"`
	// free-text search across workflow name or ID substring
	Search *string `json:"-" url:"search,omitempty"`
	// filter by workflow status (lowercase)
	Status []string `json:"-" url:"status,omitempty"`
	// filter by device platform (lowercase)
	Platform []string `json:"-" url:"platform,omitempty"`
	// only workflows created at/after this RFC3339 time
	CreatedAfter *string `json:"-" url:"created_after,omitempty"`
	// only workflows created at/before this RFC3339 time
	CreatedBefore *string `json:"-" url:"created_before,omitempty"`
	// only workflows last run at/after this RFC3339 time
	LastRunAfter *string `json:"-" url:"last_run_after,omitempty"`
	// only workflows last run at/before this RFC3339 time
	LastRunBefore *string `json:"-" url:"last_run_before,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowsListRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetLimit(limit *int64) {
	w.Limit = limit
	w.require(workflowsListRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetOffset(offset *int64) {
	w.Offset = offset
	w.require(workflowsListRequestFieldOffset)
}

// SetSearch sets the Search field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetSearch(search *string) {
	w.Search = search
	w.require(workflowsListRequestFieldSearch)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetStatus(status []string) {
	w.Status = status
	w.require(workflowsListRequestFieldStatus)
}

// SetPlatform sets the Platform field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetPlatform(platform []string) {
	w.Platform = platform
	w.require(workflowsListRequestFieldPlatform)
}

// SetCreatedAfter sets the CreatedAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetCreatedAfter(createdAfter *string) {
	w.CreatedAfter = createdAfter
	w.require(workflowsListRequestFieldCreatedAfter)
}

// SetCreatedBefore sets the CreatedBefore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetCreatedBefore(createdBefore *string) {
	w.CreatedBefore = createdBefore
	w.require(workflowsListRequestFieldCreatedBefore)
}

// SetLastRunAfter sets the LastRunAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetLastRunAfter(lastRunAfter *string) {
	w.LastRunAfter = lastRunAfter
	w.require(workflowsListRequestFieldLastRunAfter)
}

// SetLastRunBefore sets the LastRunBefore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRequest) SetLastRunBefore(lastRunBefore *string) {
	w.LastRunBefore = lastRunBefore
	w.require(workflowsListRequestFieldLastRunBefore)
}

var (
	workflowsListRevisionsRequestFieldWorkflowID = big.NewInt(1 << 0)
	workflowsListRevisionsRequestFieldLimit      = big.NewInt(1 << 1)
	workflowsListRevisionsRequestFieldBefore     = big.NewInt(1 << 2)
)

type WorkflowsListRevisionsRequest struct {
	// workflow identifier
	WorkflowID string `json:"-" url:"-"`
	Limit      *int64 `json:"-" url:"limit,omitempty"`
	// cursor: return revisions older than this revision number
	Before *int64 `json:"-" url:"before,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowsListRevisionsRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRevisionsRequest) SetWorkflowID(workflowID string) {
	w.WorkflowID = workflowID
	w.require(workflowsListRevisionsRequestFieldWorkflowID)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRevisionsRequest) SetLimit(limit *int64) {
	w.Limit = limit
	w.require(workflowsListRevisionsRequestFieldLimit)
}

// SetBefore sets the Before field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowsListRevisionsRequest) SetBefore(before *int64) {
	w.Before = before
	w.require(workflowsListRevisionsRequestFieldBefore)
}

var (
	workflowRestoreRevisionRequestFieldWorkflowID = big.NewInt(1 << 0)
	workflowRestoreRevisionRequestFieldRevisionID = big.NewInt(1 << 1)
)

type WorkflowRestoreRevisionRequest struct {
	// workflow identifier
	WorkflowID string `json:"-" url:"-"`
	// Revision to restore.
	RevisionID string `json:"revision_id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowRestoreRevisionRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRestoreRevisionRequest) SetWorkflowID(workflowID string) {
	w.WorkflowID = workflowID
	w.require(workflowRestoreRevisionRequestFieldWorkflowID)
}

// SetRevisionID sets the RevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRestoreRevisionRequest) SetRevisionID(revisionID string) {
	w.RevisionID = revisionID
	w.require(workflowRestoreRevisionRequestFieldRevisionID)
}

func (w *WorkflowRestoreRevisionRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowRestoreRevisionRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*w = WorkflowRestoreRevisionRequest(body)
	return nil
}

func (w *WorkflowRestoreRevisionRequest) MarshalJSON() ([]byte, error) {
	type embed WorkflowRestoreRevisionRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	workflowSaveCodeRequestFieldWorkflowID = big.NewInt(1 << 0)
	workflowSaveCodeRequestFieldMessage    = big.NewInt(1 << 1)
	workflowSaveCodeRequestFieldSource     = big.NewInt(1 << 2)
)

type WorkflowSaveCodeRequest struct {
	// workflow identifier
	WorkflowID string `json:"-" url:"-"`
	// Optional commit-style note.
	Message *string `json:"message,omitempty" url:"-"`
	// Python source the user typed.
	Source string `json:"source" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowSaveCodeRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSaveCodeRequest) SetWorkflowID(workflowID string) {
	w.WorkflowID = workflowID
	w.require(workflowSaveCodeRequestFieldWorkflowID)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSaveCodeRequest) SetMessage(message *string) {
	w.Message = message
	w.require(workflowSaveCodeRequestFieldMessage)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSaveCodeRequest) SetSource(source string) {
	w.Source = source
	w.require(workflowSaveCodeRequestFieldSource)
}

func (w *WorkflowSaveCodeRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowSaveCodeRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*w = WorkflowSaveCodeRequest(body)
	return nil
}

func (w *WorkflowSaveCodeRequest) MarshalJSON() ([]byte, error) {
	type embed WorkflowSaveCodeRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// Simple confirmation message.
var (
	messageOutputBodyFieldSchema  = big.NewInt(1 << 0)
	messageOutputBodyFieldMessage = big.NewInt(1 << 1)
)

type MessageOutputBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Human-readable result message.
	Message string `json:"message" url:"message"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MessageOutputBody) GetSchema() *string {
	if m == nil {
		return nil
	}
	return m.Schema
}

func (m *MessageOutputBody) GetMessage() string {
	if m == nil {
		return ""
	}
	return m.Message
}

func (m *MessageOutputBody) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MessageOutputBody) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MessageOutputBody) SetSchema(schema *string) {
	m.Schema = schema
	m.require(messageOutputBodyFieldSchema)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MessageOutputBody) SetMessage(message string) {
	m.Message = message
	m.require(messageOutputBodyFieldMessage)
}

func (m *MessageOutputBody) UnmarshalJSON(data []byte) error {
	type unmarshaler MessageOutputBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MessageOutputBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MessageOutputBody) MarshalJSON() ([]byte, error) {
	type embed MessageOutputBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MessageOutputBody) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

// Returned after successfully creating a workflow.
var (
	workflowCreateResponseFieldSchema     = big.NewInt(1 << 0)
	workflowCreateResponseFieldRevision   = big.NewInt(1 << 1)
	workflowCreateResponseFieldRevisionID = big.NewInt(1 << 2)
	workflowCreateResponseFieldWorkflowID = big.NewInt(1 << 3)
)

type WorkflowCreateResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Revision number of the first code revision (1), when code was provided.
	Revision *int64 `json:"revision,omitempty" url:"revision,omitempty"`
	// Id of the first code revision, when code was provided.
	RevisionID *string `json:"revision_id,omitempty" url:"revision_id,omitempty"`
	// Identifier assigned to the new workflow.
	WorkflowID string `json:"workflow_id" url:"workflow_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkflowCreateResponse) GetSchema() *string {
	if w == nil {
		return nil
	}
	return w.Schema
}

func (w *WorkflowCreateResponse) GetRevision() *int64 {
	if w == nil {
		return nil
	}
	return w.Revision
}

func (w *WorkflowCreateResponse) GetRevisionID() *string {
	if w == nil {
		return nil
	}
	return w.RevisionID
}

func (w *WorkflowCreateResponse) GetWorkflowID() string {
	if w == nil {
		return ""
	}
	return w.WorkflowID
}

func (w *WorkflowCreateResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WorkflowCreateResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowCreateResponse) SetSchema(schema *string) {
	w.Schema = schema
	w.require(workflowCreateResponseFieldSchema)
}

// SetRevision sets the Revision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowCreateResponse) SetRevision(revision *int64) {
	w.Revision = revision
	w.require(workflowCreateResponseFieldRevision)
}

// SetRevisionID sets the RevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowCreateResponse) SetRevisionID(revisionID *string) {
	w.RevisionID = revisionID
	w.require(workflowCreateResponseFieldRevisionID)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowCreateResponse) SetWorkflowID(workflowID string) {
	w.WorkflowID = workflowID
	w.require(workflowCreateResponseFieldWorkflowID)
}

func (w *WorkflowCreateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowCreateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowCreateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowCreateResponse) MarshalJSON() ([]byte, error) {
	type embed WorkflowCreateResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WorkflowCreateResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// Returned from GET /workflows/:id/code.
var (
	workflowGetCodeResponseFieldSchema     = big.NewInt(1 << 0)
	workflowGetCodeResponseFieldRevision   = big.NewInt(1 << 1)
	workflowGetCodeResponseFieldRevisionID = big.NewInt(1 << 2)
	workflowGetCodeResponseFieldSource     = big.NewInt(1 << 3)
	workflowGetCodeResponseFieldUpdatedAt  = big.NewInt(1 << 4)
)

type WorkflowGetCodeResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Current revision number, or 0 when no revisions exist.
	Revision int64 `json:"revision" url:"revision"`
	// Current revision's id, or null when no revisions exist.
	RevisionID *string `json:"revision_id,omitempty" url:"revision_id,omitempty"`
	// Current revision's Python source.
	Source string `json:"source" url:"source"`
	// Created_at of the current revision, or the workflow's update_date when no revisions exist.
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkflowGetCodeResponse) GetSchema() *string {
	if w == nil {
		return nil
	}
	return w.Schema
}

func (w *WorkflowGetCodeResponse) GetRevision() int64 {
	if w == nil {
		return 0
	}
	return w.Revision
}

func (w *WorkflowGetCodeResponse) GetRevisionID() *string {
	if w == nil {
		return nil
	}
	return w.RevisionID
}

func (w *WorkflowGetCodeResponse) GetSource() string {
	if w == nil {
		return ""
	}
	return w.Source
}

func (w *WorkflowGetCodeResponse) GetUpdatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.UpdatedAt
}

func (w *WorkflowGetCodeResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WorkflowGetCodeResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowGetCodeResponse) SetSchema(schema *string) {
	w.Schema = schema
	w.require(workflowGetCodeResponseFieldSchema)
}

// SetRevision sets the Revision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowGetCodeResponse) SetRevision(revision int64) {
	w.Revision = revision
	w.require(workflowGetCodeResponseFieldRevision)
}

// SetRevisionID sets the RevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowGetCodeResponse) SetRevisionID(revisionID *string) {
	w.RevisionID = revisionID
	w.require(workflowGetCodeResponseFieldRevisionID)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowGetCodeResponse) SetSource(source string) {
	w.Source = source
	w.require(workflowGetCodeResponseFieldSource)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowGetCodeResponse) SetUpdatedAt(updatedAt time.Time) {
	w.UpdatedAt = updatedAt
	w.require(workflowGetCodeResponseFieldUpdatedAt)
}

func (w *WorkflowGetCodeResponse) UnmarshalJSON(data []byte) error {
	type embed WorkflowGetCodeResponse
	var unmarshaler = struct {
		embed
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WorkflowGetCodeResponse(unmarshaler.embed)
	w.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowGetCodeResponse) MarshalJSON() ([]byte, error) {
	type embed WorkflowGetCodeResponse
	var marshaler = struct {
		embed
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*w),
		UpdatedAt: internal.NewDateTime(w.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WorkflowGetCodeResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// Paginated list of workflows.
var (
	workflowListResponseFieldSchema    = big.NewInt(1 << 0)
	workflowListResponseFieldLimit     = big.NewInt(1 << 1)
	workflowListResponseFieldOffset    = big.NewInt(1 << 2)
	workflowListResponseFieldTotal     = big.NewInt(1 << 3)
	workflowListResponseFieldWorkflows = big.NewInt(1 << 4)
)

type WorkflowListResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Page size used for this response.
	Limit int64 `json:"limit" url:"limit"`
	// Pagination offset used for this response.
	Offset int64 `json:"offset" url:"offset"`
	// Total number of workflows matching the query.
	Total int64 `json:"total" url:"total"`
	// Page of workflow records with stats.
	Workflows []*WorkflowResponse `json:"workflows,omitempty" url:"workflows,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkflowListResponse) GetSchema() *string {
	if w == nil {
		return nil
	}
	return w.Schema
}

func (w *WorkflowListResponse) GetLimit() int64 {
	if w == nil {
		return 0
	}
	return w.Limit
}

func (w *WorkflowListResponse) GetOffset() int64 {
	if w == nil {
		return 0
	}
	return w.Offset
}

func (w *WorkflowListResponse) GetTotal() int64 {
	if w == nil {
		return 0
	}
	return w.Total
}

func (w *WorkflowListResponse) GetWorkflows() []*WorkflowResponse {
	if w == nil {
		return nil
	}
	return w.Workflows
}

func (w *WorkflowListResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WorkflowListResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowListResponse) SetSchema(schema *string) {
	w.Schema = schema
	w.require(workflowListResponseFieldSchema)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowListResponse) SetLimit(limit int64) {
	w.Limit = limit
	w.require(workflowListResponseFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowListResponse) SetOffset(offset int64) {
	w.Offset = offset
	w.require(workflowListResponseFieldOffset)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowListResponse) SetTotal(total int64) {
	w.Total = total
	w.require(workflowListResponseFieldTotal)
}

// SetWorkflows sets the Workflows field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowListResponse) SetWorkflows(workflows []*WorkflowResponse) {
	w.Workflows = workflows
	w.require(workflowListResponseFieldWorkflows)
}

func (w *WorkflowListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowListResponse) MarshalJSON() ([]byte, error) {
	type embed WorkflowListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WorkflowListResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// Returned from GET /workflows/:id/revisions.
var (
	workflowListRevisionsResponseFieldSchema    = big.NewInt(1 << 0)
	workflowListRevisionsResponseFieldRevisions = big.NewInt(1 << 1)
)

type WorkflowListRevisionsResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Page of revision summaries, newest-first.
	Revisions []*WorkflowRevisionSummary `json:"revisions,omitempty" url:"revisions,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkflowListRevisionsResponse) GetSchema() *string {
	if w == nil {
		return nil
	}
	return w.Schema
}

func (w *WorkflowListRevisionsResponse) GetRevisions() []*WorkflowRevisionSummary {
	if w == nil {
		return nil
	}
	return w.Revisions
}

func (w *WorkflowListRevisionsResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WorkflowListRevisionsResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowListRevisionsResponse) SetSchema(schema *string) {
	w.Schema = schema
	w.require(workflowListRevisionsResponseFieldSchema)
}

// SetRevisions sets the Revisions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowListRevisionsResponse) SetRevisions(revisions []*WorkflowRevisionSummary) {
	w.Revisions = revisions
	w.require(workflowListRevisionsResponseFieldRevisions)
}

func (w *WorkflowListRevisionsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowListRevisionsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowListRevisionsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowListRevisionsResponse) MarshalJSON() ([]byte, error) {
	type embed WorkflowListRevisionsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WorkflowListRevisionsResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// Full workflow record with embedded stats.
var (
	workflowResponseFieldSchema   = big.NewInt(1 << 0)
	workflowResponseFieldStats    = big.NewInt(1 << 1)
	workflowResponseFieldWorkflow = big.NewInt(1 << 2)
)

type WorkflowResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// Workflow's run statistics.
	Stats *WorkflowStats `json:"stats" url:"stats"`
	// Core workflow record.
	Workflow *WorkflowSummary `json:"workflow" url:"workflow"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkflowResponse) GetSchema() *string {
	if w == nil {
		return nil
	}
	return w.Schema
}

func (w *WorkflowResponse) GetStats() *WorkflowStats {
	if w == nil {
		return nil
	}
	return w.Stats
}

func (w *WorkflowResponse) GetWorkflow() *WorkflowSummary {
	if w == nil {
		return nil
	}
	return w.Workflow
}

func (w *WorkflowResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WorkflowResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowResponse) SetSchema(schema *string) {
	w.Schema = schema
	w.require(workflowResponseFieldSchema)
}

// SetStats sets the Stats field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowResponse) SetStats(stats *WorkflowStats) {
	w.Stats = stats
	w.require(workflowResponseFieldStats)
}

// SetWorkflow sets the Workflow field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowResponse) SetWorkflow(workflow *WorkflowSummary) {
	w.Workflow = workflow
	w.require(workflowResponseFieldWorkflow)
}

func (w *WorkflowResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowResponse) MarshalJSON() ([]byte, error) {
	type embed WorkflowResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WorkflowResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// One saved code revision, including the full code source.
var (
	workflowRevisionDetailFieldSchema       = big.NewInt(1 << 0)
	workflowRevisionDetailFieldAuthorUserID = big.NewInt(1 << 1)
	workflowRevisionDetailFieldBytes        = big.NewInt(1 << 2)
	workflowRevisionDetailFieldCodeSource   = big.NewInt(1 << 3)
	workflowRevisionDetailFieldCreatedAt    = big.NewInt(1 << 4)
	workflowRevisionDetailFieldID           = big.NewInt(1 << 5)
	workflowRevisionDetailFieldMessage      = big.NewInt(1 << 6)
	workflowRevisionDetailFieldRevision     = big.NewInt(1 << 7)
	workflowRevisionDetailFieldSha256       = big.NewInt(1 << 8)
)

type WorkflowRevisionDetail struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// User who saved the revision.
	AuthorUserID string `json:"author_user_id" url:"author_user_id"`
	// Size of the code source in bytes.
	Bytes int64 `json:"bytes" url:"bytes"`
	// Full code source of the revision.
	CodeSource string `json:"code_source" url:"code_source"`
	// When the revision was saved.
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// Revision identifier.
	ID string `json:"id" url:"id"`
	// Optional commit-style message.
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Monotonic revision number, starting at 1.
	Revision int64 `json:"revision" url:"revision"`
	// SHA-256 of the code source.
	Sha256 string `json:"sha256" url:"sha256"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkflowRevisionDetail) GetSchema() *string {
	if w == nil {
		return nil
	}
	return w.Schema
}

func (w *WorkflowRevisionDetail) GetAuthorUserID() string {
	if w == nil {
		return ""
	}
	return w.AuthorUserID
}

func (w *WorkflowRevisionDetail) GetBytes() int64 {
	if w == nil {
		return 0
	}
	return w.Bytes
}

func (w *WorkflowRevisionDetail) GetCodeSource() string {
	if w == nil {
		return ""
	}
	return w.CodeSource
}

func (w *WorkflowRevisionDetail) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *WorkflowRevisionDetail) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WorkflowRevisionDetail) GetMessage() *string {
	if w == nil {
		return nil
	}
	return w.Message
}

func (w *WorkflowRevisionDetail) GetRevision() int64 {
	if w == nil {
		return 0
	}
	return w.Revision
}

func (w *WorkflowRevisionDetail) GetSha256() string {
	if w == nil {
		return ""
	}
	return w.Sha256
}

func (w *WorkflowRevisionDetail) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WorkflowRevisionDetail) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionDetail) SetSchema(schema *string) {
	w.Schema = schema
	w.require(workflowRevisionDetailFieldSchema)
}

// SetAuthorUserID sets the AuthorUserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionDetail) SetAuthorUserID(authorUserID string) {
	w.AuthorUserID = authorUserID
	w.require(workflowRevisionDetailFieldAuthorUserID)
}

// SetBytes sets the Bytes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionDetail) SetBytes(bytes int64) {
	w.Bytes = bytes
	w.require(workflowRevisionDetailFieldBytes)
}

// SetCodeSource sets the CodeSource field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionDetail) SetCodeSource(codeSource string) {
	w.CodeSource = codeSource
	w.require(workflowRevisionDetailFieldCodeSource)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionDetail) SetCreatedAt(createdAt time.Time) {
	w.CreatedAt = createdAt
	w.require(workflowRevisionDetailFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionDetail) SetID(id string) {
	w.ID = id
	w.require(workflowRevisionDetailFieldID)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionDetail) SetMessage(message *string) {
	w.Message = message
	w.require(workflowRevisionDetailFieldMessage)
}

// SetRevision sets the Revision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionDetail) SetRevision(revision int64) {
	w.Revision = revision
	w.require(workflowRevisionDetailFieldRevision)
}

// SetSha256 sets the Sha256 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionDetail) SetSha256(sha256 string) {
	w.Sha256 = sha256
	w.require(workflowRevisionDetailFieldSha256)
}

func (w *WorkflowRevisionDetail) UnmarshalJSON(data []byte) error {
	type embed WorkflowRevisionDetail
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WorkflowRevisionDetail(unmarshaler.embed)
	w.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowRevisionDetail) MarshalJSON() ([]byte, error) {
	type embed WorkflowRevisionDetail
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed:     embed(*w),
		CreatedAt: internal.NewDateTime(w.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WorkflowRevisionDetail) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// One saved code revision, without the source body.
var (
	workflowRevisionSummaryFieldAuthorUserID = big.NewInt(1 << 0)
	workflowRevisionSummaryFieldBytes        = big.NewInt(1 << 1)
	workflowRevisionSummaryFieldCreatedAt    = big.NewInt(1 << 2)
	workflowRevisionSummaryFieldID           = big.NewInt(1 << 3)
	workflowRevisionSummaryFieldMessage      = big.NewInt(1 << 4)
	workflowRevisionSummaryFieldRevision     = big.NewInt(1 << 5)
	workflowRevisionSummaryFieldSha256       = big.NewInt(1 << 6)
)

type WorkflowRevisionSummary struct {
	// User who saved the revision.
	AuthorUserID string `json:"author_user_id" url:"author_user_id"`
	// Size of the code source in bytes.
	Bytes int64 `json:"bytes" url:"bytes"`
	// When the revision was saved.
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// Revision identifier.
	ID string `json:"id" url:"id"`
	// Optional commit-style message.
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// Monotonic revision number, starting at 1.
	Revision int64 `json:"revision" url:"revision"`
	// SHA-256 of the code source.
	Sha256 string `json:"sha256" url:"sha256"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkflowRevisionSummary) GetAuthorUserID() string {
	if w == nil {
		return ""
	}
	return w.AuthorUserID
}

func (w *WorkflowRevisionSummary) GetBytes() int64 {
	if w == nil {
		return 0
	}
	return w.Bytes
}

func (w *WorkflowRevisionSummary) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *WorkflowRevisionSummary) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WorkflowRevisionSummary) GetMessage() *string {
	if w == nil {
		return nil
	}
	return w.Message
}

func (w *WorkflowRevisionSummary) GetRevision() int64 {
	if w == nil {
		return 0
	}
	return w.Revision
}

func (w *WorkflowRevisionSummary) GetSha256() string {
	if w == nil {
		return ""
	}
	return w.Sha256
}

func (w *WorkflowRevisionSummary) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WorkflowRevisionSummary) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetAuthorUserID sets the AuthorUserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionSummary) SetAuthorUserID(authorUserID string) {
	w.AuthorUserID = authorUserID
	w.require(workflowRevisionSummaryFieldAuthorUserID)
}

// SetBytes sets the Bytes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionSummary) SetBytes(bytes int64) {
	w.Bytes = bytes
	w.require(workflowRevisionSummaryFieldBytes)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionSummary) SetCreatedAt(createdAt time.Time) {
	w.CreatedAt = createdAt
	w.require(workflowRevisionSummaryFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionSummary) SetID(id string) {
	w.ID = id
	w.require(workflowRevisionSummaryFieldID)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionSummary) SetMessage(message *string) {
	w.Message = message
	w.require(workflowRevisionSummaryFieldMessage)
}

// SetRevision sets the Revision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionSummary) SetRevision(revision int64) {
	w.Revision = revision
	w.require(workflowRevisionSummaryFieldRevision)
}

// SetSha256 sets the Sha256 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowRevisionSummary) SetSha256(sha256 string) {
	w.Sha256 = sha256
	w.require(workflowRevisionSummaryFieldSha256)
}

func (w *WorkflowRevisionSummary) UnmarshalJSON(data []byte) error {
	type embed WorkflowRevisionSummary
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WorkflowRevisionSummary(unmarshaler.embed)
	w.CreatedAt = unmarshaler.CreatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowRevisionSummary) MarshalJSON() ([]byte, error) {
	type embed WorkflowRevisionSummary
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
	}{
		embed:     embed(*w),
		CreatedAt: internal.NewDateTime(w.CreatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WorkflowRevisionSummary) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// Returned from POST /workflows/:id/code.
var (
	workflowSaveCodeResponseFieldSchema     = big.NewInt(1 << 0)
	workflowSaveCodeResponseFieldNoOp       = big.NewInt(1 << 1)
	workflowSaveCodeResponseFieldRevision   = big.NewInt(1 << 2)
	workflowSaveCodeResponseFieldRevisionID = big.NewInt(1 << 3)
)

type WorkflowSaveCodeResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" url:"$schema,omitempty"`
	// True when the submitted source's sha256 matched the prior current revision; no new row was inserted, no pointer was changed.
	NoOp bool `json:"no_op" url:"no_op"`
	// Per-workflow monotonic revision number.
	Revision int64 `json:"revision" url:"revision"`
	// Workflow_revisions.id of the active revision after the save.
	RevisionID string `json:"revision_id" url:"revision_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkflowSaveCodeResponse) GetSchema() *string {
	if w == nil {
		return nil
	}
	return w.Schema
}

func (w *WorkflowSaveCodeResponse) GetNoOp() bool {
	if w == nil {
		return false
	}
	return w.NoOp
}

func (w *WorkflowSaveCodeResponse) GetRevision() int64 {
	if w == nil {
		return 0
	}
	return w.Revision
}

func (w *WorkflowSaveCodeResponse) GetRevisionID() string {
	if w == nil {
		return ""
	}
	return w.RevisionID
}

func (w *WorkflowSaveCodeResponse) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WorkflowSaveCodeResponse) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSaveCodeResponse) SetSchema(schema *string) {
	w.Schema = schema
	w.require(workflowSaveCodeResponseFieldSchema)
}

// SetNoOp sets the NoOp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSaveCodeResponse) SetNoOp(noOp bool) {
	w.NoOp = noOp
	w.require(workflowSaveCodeResponseFieldNoOp)
}

// SetRevision sets the Revision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSaveCodeResponse) SetRevision(revision int64) {
	w.Revision = revision
	w.require(workflowSaveCodeResponseFieldRevision)
}

// SetRevisionID sets the RevisionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSaveCodeResponse) SetRevisionID(revisionID string) {
	w.RevisionID = revisionID
	w.require(workflowSaveCodeResponseFieldRevisionID)
}

func (w *WorkflowSaveCodeResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowSaveCodeResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowSaveCodeResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowSaveCodeResponse) MarshalJSON() ([]byte, error) {
	type embed WorkflowSaveCodeResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WorkflowSaveCodeResponse) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// WorkflowStats summarizes run statistics for a workflow.
var (
	workflowStatsFieldSuccessRate = big.NewInt(1 << 0)
	workflowStatsFieldTotalRuns   = big.NewInt(1 << 1)
)

type WorkflowStats struct {
	// Fraction of runs that completed successfully, from 0.0 to 1.0 (multiply by 100 for a percentage).
	SuccessRate float64 `json:"success_rate" url:"success_rate"`
	// Total number of runs for this workflow.
	TotalRuns int64 `json:"total_runs" url:"total_runs"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkflowStats) GetSuccessRate() float64 {
	if w == nil {
		return 0
	}
	return w.SuccessRate
}

func (w *WorkflowStats) GetTotalRuns() int64 {
	if w == nil {
		return 0
	}
	return w.TotalRuns
}

func (w *WorkflowStats) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WorkflowStats) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetSuccessRate sets the SuccessRate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowStats) SetSuccessRate(successRate float64) {
	w.SuccessRate = successRate
	w.require(workflowStatsFieldSuccessRate)
}

// SetTotalRuns sets the TotalRuns field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowStats) SetTotalRuns(totalRuns int64) {
	w.TotalRuns = totalRuns
	w.require(workflowStatsFieldTotalRuns)
}

func (w *WorkflowStats) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowStats
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WorkflowStats(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowStats) MarshalJSON() ([]byte, error) {
	type embed WorkflowStats
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WorkflowStats) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// A workflow: a saved automation that runs against a phone.
var (
	workflowSummaryFieldCreatedAt      = big.NewInt(1 << 0)
	workflowSummaryFieldID             = big.NewInt(1 << 1)
	workflowSummaryFieldLastRunAt      = big.NewInt(1 << 2)
	workflowSummaryFieldName           = big.NewInt(1 << 3)
	workflowSummaryFieldOcrEngine      = big.NewInt(1 << 4)
	workflowSummaryFieldOrganizationID = big.NewInt(1 << 5)
	workflowSummaryFieldPlatform       = big.NewInt(1 << 6)
	workflowSummaryFieldStatus         = big.NewInt(1 << 7)
	workflowSummaryFieldUpdatedAt      = big.NewInt(1 << 8)
	workflowSummaryFieldUserID         = big.NewInt(1 << 9)
)

type WorkflowSummary struct {
	// When the workflow was created.
	CreatedAt time.Time `json:"created_at" url:"created_at"`
	// Workflow identifier.
	ID string `json:"id" url:"id"`
	// When the workflow last ran; absent if never run.
	LastRunAt *time.Time `json:"last_run_at,omitempty" url:"last_run_at,omitempty"`
	// Workflow name.
	Name string `json:"name" url:"name"`
	// OCR engine the workflow runs with.
	OcrEngine WorkflowSummaryOcrEngine `json:"ocr_engine" url:"ocr_engine"`
	// Organization the workflow belongs to.
	OrganizationID *string `json:"organization_id,omitempty" url:"organization_id,omitempty"`
	// Target platform.
	Platform WorkflowSummaryPlatform `json:"platform" url:"platform"`
	// Workflow lifecycle status.
	Status WorkflowSummaryStatus `json:"status" url:"status"`
	// When the workflow was last updated.
	UpdatedAt time.Time `json:"updated_at" url:"updated_at"`
	// User who created the workflow.
	UserID string `json:"user_id" url:"user_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WorkflowSummary) GetCreatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.CreatedAt
}

func (w *WorkflowSummary) GetID() string {
	if w == nil {
		return ""
	}
	return w.ID
}

func (w *WorkflowSummary) GetLastRunAt() *time.Time {
	if w == nil {
		return nil
	}
	return w.LastRunAt
}

func (w *WorkflowSummary) GetName() string {
	if w == nil {
		return ""
	}
	return w.Name
}

func (w *WorkflowSummary) GetOcrEngine() WorkflowSummaryOcrEngine {
	if w == nil {
		return ""
	}
	return w.OcrEngine
}

func (w *WorkflowSummary) GetOrganizationID() *string {
	if w == nil {
		return nil
	}
	return w.OrganizationID
}

func (w *WorkflowSummary) GetPlatform() WorkflowSummaryPlatform {
	if w == nil {
		return ""
	}
	return w.Platform
}

func (w *WorkflowSummary) GetStatus() WorkflowSummaryStatus {
	if w == nil {
		return ""
	}
	return w.Status
}

func (w *WorkflowSummary) GetUpdatedAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.UpdatedAt
}

func (w *WorkflowSummary) GetUserID() string {
	if w == nil {
		return ""
	}
	return w.UserID
}

func (w *WorkflowSummary) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WorkflowSummary) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSummary) SetCreatedAt(createdAt time.Time) {
	w.CreatedAt = createdAt
	w.require(workflowSummaryFieldCreatedAt)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSummary) SetID(id string) {
	w.ID = id
	w.require(workflowSummaryFieldID)
}

// SetLastRunAt sets the LastRunAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSummary) SetLastRunAt(lastRunAt *time.Time) {
	w.LastRunAt = lastRunAt
	w.require(workflowSummaryFieldLastRunAt)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSummary) SetName(name string) {
	w.Name = name
	w.require(workflowSummaryFieldName)
}

// SetOcrEngine sets the OcrEngine field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSummary) SetOcrEngine(ocrEngine WorkflowSummaryOcrEngine) {
	w.OcrEngine = ocrEngine
	w.require(workflowSummaryFieldOcrEngine)
}

// SetOrganizationID sets the OrganizationID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSummary) SetOrganizationID(organizationID *string) {
	w.OrganizationID = organizationID
	w.require(workflowSummaryFieldOrganizationID)
}

// SetPlatform sets the Platform field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSummary) SetPlatform(platform WorkflowSummaryPlatform) {
	w.Platform = platform
	w.require(workflowSummaryFieldPlatform)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSummary) SetStatus(status WorkflowSummaryStatus) {
	w.Status = status
	w.require(workflowSummaryFieldStatus)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSummary) SetUpdatedAt(updatedAt time.Time) {
	w.UpdatedAt = updatedAt
	w.require(workflowSummaryFieldUpdatedAt)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowSummary) SetUserID(userID string) {
	w.UserID = userID
	w.require(workflowSummaryFieldUserID)
}

func (w *WorkflowSummary) UnmarshalJSON(data []byte) error {
	type embed WorkflowSummary
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		LastRunAt *internal.DateTime `json:"last_run_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed: embed(*w),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*w = WorkflowSummary(unmarshaler.embed)
	w.CreatedAt = unmarshaler.CreatedAt.Time()
	w.LastRunAt = unmarshaler.LastRunAt.TimePtr()
	w.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WorkflowSummary) MarshalJSON() ([]byte, error) {
	type embed WorkflowSummary
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"created_at"`
		LastRunAt *internal.DateTime `json:"last_run_at,omitempty"`
		UpdatedAt *internal.DateTime `json:"updated_at"`
	}{
		embed:     embed(*w),
		CreatedAt: internal.NewDateTime(w.CreatedAt),
		LastRunAt: internal.NewOptionalDateTime(w.LastRunAt),
		UpdatedAt: internal.NewDateTime(w.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WorkflowSummary) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

// OCR engine the workflow runs with.
type WorkflowSummaryOcrEngine string

const (
	WorkflowSummaryOcrEngineFree    WorkflowSummaryOcrEngine = "free"
	WorkflowSummaryOcrEnginePremium WorkflowSummaryOcrEngine = "premium"
)

func NewWorkflowSummaryOcrEngineFromString(s string) (WorkflowSummaryOcrEngine, error) {
	switch s {
	case "free":
		return WorkflowSummaryOcrEngineFree, nil
	case "premium":
		return WorkflowSummaryOcrEnginePremium, nil
	}
	var t WorkflowSummaryOcrEngine
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WorkflowSummaryOcrEngine) Ptr() *WorkflowSummaryOcrEngine {
	return &w
}

// Target platform.
type WorkflowSummaryPlatform string

const (
	WorkflowSummaryPlatformAndroid WorkflowSummaryPlatform = "android"
	WorkflowSummaryPlatformIos     WorkflowSummaryPlatform = "ios"
	WorkflowSummaryPlatformBoth    WorkflowSummaryPlatform = "both"
)

func NewWorkflowSummaryPlatformFromString(s string) (WorkflowSummaryPlatform, error) {
	switch s {
	case "android":
		return WorkflowSummaryPlatformAndroid, nil
	case "ios":
		return WorkflowSummaryPlatformIos, nil
	case "both":
		return WorkflowSummaryPlatformBoth, nil
	}
	var t WorkflowSummaryPlatform
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WorkflowSummaryPlatform) Ptr() *WorkflowSummaryPlatform {
	return &w
}

// Workflow lifecycle status.
type WorkflowSummaryStatus string

const (
	WorkflowSummaryStatusReady    WorkflowSummaryStatus = "ready"
	WorkflowSummaryStatusTraining WorkflowSummaryStatus = "training"
	WorkflowSummaryStatusRunning  WorkflowSummaryStatus = "running"
)

func NewWorkflowSummaryStatusFromString(s string) (WorkflowSummaryStatus, error) {
	switch s {
	case "ready":
		return WorkflowSummaryStatusReady, nil
	case "training":
		return WorkflowSummaryStatusTraining, nil
	case "running":
		return WorkflowSummaryStatusRunning, nil
	}
	var t WorkflowSummaryStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WorkflowSummaryStatus) Ptr() *WorkflowSummaryStatus {
	return &w
}

// OCR backend to use.
type WorkflowCreateRequestOcrEngine string

const (
	WorkflowCreateRequestOcrEngineFree    WorkflowCreateRequestOcrEngine = "free"
	WorkflowCreateRequestOcrEnginePremium WorkflowCreateRequestOcrEngine = "premium"
)

func NewWorkflowCreateRequestOcrEngineFromString(s string) (WorkflowCreateRequestOcrEngine, error) {
	switch s {
	case "free":
		return WorkflowCreateRequestOcrEngineFree, nil
	case "premium":
		return WorkflowCreateRequestOcrEnginePremium, nil
	}
	var t WorkflowCreateRequestOcrEngine
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WorkflowCreateRequestOcrEngine) Ptr() *WorkflowCreateRequestOcrEngine {
	return &w
}

// Target OS platform.
type WorkflowCreateRequestPlatform string

const (
	WorkflowCreateRequestPlatformIos     WorkflowCreateRequestPlatform = "ios"
	WorkflowCreateRequestPlatformAndroid WorkflowCreateRequestPlatform = "android"
	WorkflowCreateRequestPlatformBoth    WorkflowCreateRequestPlatform = "both"
)

func NewWorkflowCreateRequestPlatformFromString(s string) (WorkflowCreateRequestPlatform, error) {
	switch s {
	case "ios":
		return WorkflowCreateRequestPlatformIos, nil
	case "android":
		return WorkflowCreateRequestPlatformAndroid, nil
	case "both":
		return WorkflowCreateRequestPlatformBoth, nil
	}
	var t WorkflowCreateRequestPlatform
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WorkflowCreateRequestPlatform) Ptr() *WorkflowCreateRequestPlatform {
	return &w
}

// Updated OCR backend selection.
type WorkflowUpdateRequestOcrEngine string

const (
	WorkflowUpdateRequestOcrEngineFree    WorkflowUpdateRequestOcrEngine = "free"
	WorkflowUpdateRequestOcrEnginePremium WorkflowUpdateRequestOcrEngine = "premium"
)

func NewWorkflowUpdateRequestOcrEngineFromString(s string) (WorkflowUpdateRequestOcrEngine, error) {
	switch s {
	case "free":
		return WorkflowUpdateRequestOcrEngineFree, nil
	case "premium":
		return WorkflowUpdateRequestOcrEnginePremium, nil
	}
	var t WorkflowUpdateRequestOcrEngine
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WorkflowUpdateRequestOcrEngine) Ptr() *WorkflowUpdateRequestOcrEngine {
	return &w
}

// Updated target platform.
type WorkflowUpdateRequestPlatform string

const (
	WorkflowUpdateRequestPlatformIos     WorkflowUpdateRequestPlatform = "ios"
	WorkflowUpdateRequestPlatformAndroid WorkflowUpdateRequestPlatform = "android"
	WorkflowUpdateRequestPlatformBoth    WorkflowUpdateRequestPlatform = "both"
)

func NewWorkflowUpdateRequestPlatformFromString(s string) (WorkflowUpdateRequestPlatform, error) {
	switch s {
	case "ios":
		return WorkflowUpdateRequestPlatformIos, nil
	case "android":
		return WorkflowUpdateRequestPlatformAndroid, nil
	case "both":
		return WorkflowUpdateRequestPlatformBoth, nil
	}
	var t WorkflowUpdateRequestPlatform
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WorkflowUpdateRequestPlatform) Ptr() *WorkflowUpdateRequestPlatform {
	return &w
}

// Updated lifecycle status.
type WorkflowUpdateRequestStatus string

const (
	WorkflowUpdateRequestStatusReady    WorkflowUpdateRequestStatus = "ready"
	WorkflowUpdateRequestStatusTraining WorkflowUpdateRequestStatus = "training"
	WorkflowUpdateRequestStatusRunning  WorkflowUpdateRequestStatus = "running"
)

func NewWorkflowUpdateRequestStatusFromString(s string) (WorkflowUpdateRequestStatus, error) {
	switch s {
	case "ready":
		return WorkflowUpdateRequestStatusReady, nil
	case "training":
		return WorkflowUpdateRequestStatusTraining, nil
	case "running":
		return WorkflowUpdateRequestStatusRunning, nil
	}
	var t WorkflowUpdateRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (w WorkflowUpdateRequestStatus) Ptr() *WorkflowUpdateRequestStatus {
	return &w
}

var (
	workflowUpdateRequestFieldWorkflowID = big.NewInt(1 << 0)
	workflowUpdateRequestFieldName       = big.NewInt(1 << 1)
	workflowUpdateRequestFieldOcrEngine  = big.NewInt(1 << 2)
	workflowUpdateRequestFieldPlatform   = big.NewInt(1 << 3)
	workflowUpdateRequestFieldStatus     = big.NewInt(1 << 4)
)

type WorkflowUpdateRequest struct {
	// workflow identifier
	WorkflowID string `json:"-" url:"-"`
	// Updated workflow name.
	Name *string `json:"name,omitempty" url:"-"`
	// Updated OCR backend selection.
	OcrEngine *WorkflowUpdateRequestOcrEngine `json:"ocr_engine,omitempty" url:"-"`
	// Updated target platform.
	Platform *WorkflowUpdateRequestPlatform `json:"platform,omitempty" url:"-"`
	// Updated lifecycle status.
	Status *WorkflowUpdateRequestStatus `json:"status,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (w *WorkflowUpdateRequest) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetWorkflowID sets the WorkflowID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowUpdateRequest) SetWorkflowID(workflowID string) {
	w.WorkflowID = workflowID
	w.require(workflowUpdateRequestFieldWorkflowID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowUpdateRequest) SetName(name *string) {
	w.Name = name
	w.require(workflowUpdateRequestFieldName)
}

// SetOcrEngine sets the OcrEngine field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowUpdateRequest) SetOcrEngine(ocrEngine *WorkflowUpdateRequestOcrEngine) {
	w.OcrEngine = ocrEngine
	w.require(workflowUpdateRequestFieldOcrEngine)
}

// SetPlatform sets the Platform field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowUpdateRequest) SetPlatform(platform *WorkflowUpdateRequestPlatform) {
	w.Platform = platform
	w.require(workflowUpdateRequestFieldPlatform)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WorkflowUpdateRequest) SetStatus(status *WorkflowUpdateRequestStatus) {
	w.Status = status
	w.require(workflowUpdateRequestFieldStatus)
}

func (w *WorkflowUpdateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler WorkflowUpdateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*w = WorkflowUpdateRequest(body)
	return nil
}

func (w *WorkflowUpdateRequest) MarshalJSON() ([]byte, error) {
	type embed WorkflowUpdateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}
