// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersAccessibilityTreeLocateRequest(t *testing.T) {
	t.Run("SetImage", func(t *testing.T) {
		obj := &AccessibilityTreeLocateRequest{}
		var fernTestValueImage *string
		obj.SetImage(fernTestValueImage)
		assert.Equal(t, fernTestValueImage, obj.Image)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetModel", func(t *testing.T) {
		obj := &AccessibilityTreeLocateRequest{}
		var fernTestValueModel *string
		obj.SetModel(fernTestValueModel)
		assert.Equal(t, fernTestValueModel, obj.Model)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNodes", func(t *testing.T) {
		obj := &AccessibilityTreeLocateRequest{}
		var fernTestValueNodes []*AccessibilityTreeNode
		obj.SetNodes(fernTestValueNodes)
		assert.Equal(t, fernTestValueNodes, obj.Nodes)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetQuery", func(t *testing.T) {
		obj := &AccessibilityTreeLocateRequest{}
		var fernTestValueQuery string
		obj.SetQuery(fernTestValueQuery)
		assert.Equal(t, fernTestValueQuery, obj.Query)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitAccessibilityTreeLocateRequest(t *testing.T) {
	t.Run("SetImage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateRequest{}
		var fernTestValueImage *string

		// Act
		obj.SetImage(fernTestValueImage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetModel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateRequest{}
		var fernTestValueModel *string

		// Act
		obj.SetModel(fernTestValueModel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNodes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateRequest{}
		var fernTestValueNodes []*AccessibilityTreeNode

		// Act
		obj.SetNodes(fernTestValueNodes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetQuery_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateRequest{}
		var fernTestValueQuery string

		// Act
		obj.SetQuery(fernTestValueQuery)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersAccessibilityTreeLocateResponse(t *testing.T) {
	t.Run("SetCompletionTokens", func(t *testing.T) {
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueCompletionTokens *int
		obj.SetCompletionTokens(fernTestValueCompletionTokens)
		assert.Equal(t, fernTestValueCompletionTokens, obj.CompletionTokens)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetConfidence", func(t *testing.T) {
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueConfidence float64
		obj.SetConfidence(fernTestValueConfidence)
		assert.Equal(t, fernTestValueConfidence, obj.Confidence)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCostMicrodollars", func(t *testing.T) {
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueCostMicrodollars int
		obj.SetCostMicrodollars(fernTestValueCostMicrodollars)
		assert.Equal(t, fernTestValueCostMicrodollars, obj.CostMicrodollars)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFound", func(t *testing.T) {
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueFound bool
		obj.SetFound(fernTestValueFound)
		assert.Equal(t, fernTestValueFound, obj.Found)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLatencyMs", func(t *testing.T) {
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueLatencyMs int
		obj.SetLatencyMs(fernTestValueLatencyMs)
		assert.Equal(t, fernTestValueLatencyMs, obj.LatencyMs)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetModel", func(t *testing.T) {
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueModel string
		obj.SetModel(fernTestValueModel)
		assert.Equal(t, fernTestValueModel, obj.Model)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNodeID", func(t *testing.T) {
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueNodeID *string
		obj.SetNodeID(fernTestValueNodeID)
		assert.Equal(t, fernTestValueNodeID, obj.NodeID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPromptTokens", func(t *testing.T) {
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValuePromptTokens *int
		obj.SetPromptTokens(fernTestValuePromptTokens)
		assert.Equal(t, fernTestValuePromptTokens, obj.PromptTokens)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersAccessibilityTreeLocateResponse(t *testing.T) {
	t.Run("GetCompletionTokens", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var expected *int
		obj.CompletionTokens = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCompletionTokens(), "getter should return the property value")
	})

	t.Run("GetCompletionTokens_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		obj.CompletionTokens = nil

		// Act & Assert
		assert.Nil(t, obj.GetCompletionTokens(), "getter should return nil when property is nil")
	})

	t.Run("GetCompletionTokens_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeLocateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCompletionTokens() // Should return zero value
	})

	t.Run("GetConfidence", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var expected float64
		obj.Confidence = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetConfidence(), "getter should return the property value")
	})

	t.Run("GetConfidence_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeLocateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetConfidence() // Should return zero value
	})

	t.Run("GetCostMicrodollars", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var expected int
		obj.CostMicrodollars = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCostMicrodollars(), "getter should return the property value")
	})

	t.Run("GetCostMicrodollars_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeLocateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCostMicrodollars() // Should return zero value
	})

	t.Run("GetFound", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var expected bool
		obj.Found = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFound(), "getter should return the property value")
	})

	t.Run("GetFound_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeLocateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFound() // Should return zero value
	})

	t.Run("GetLatencyMs", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var expected int
		obj.LatencyMs = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLatencyMs(), "getter should return the property value")
	})

	t.Run("GetLatencyMs_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeLocateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLatencyMs() // Should return zero value
	})

	t.Run("GetModel", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var expected string
		obj.Model = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetModel(), "getter should return the property value")
	})

	t.Run("GetModel_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeLocateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetModel() // Should return zero value
	})

	t.Run("GetNodeID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var expected *string
		obj.NodeID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNodeID(), "getter should return the property value")
	})

	t.Run("GetNodeID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		obj.NodeID = nil

		// Act & Assert
		assert.Nil(t, obj.GetNodeID(), "getter should return nil when property is nil")
	})

	t.Run("GetNodeID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeLocateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNodeID() // Should return zero value
	})

	t.Run("GetPromptTokens", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var expected *int
		obj.PromptTokens = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPromptTokens(), "getter should return the property value")
	})

	t.Run("GetPromptTokens_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		obj.PromptTokens = nil

		// Act & Assert
		assert.Nil(t, obj.GetPromptTokens(), "getter should return nil when property is nil")
	})

	t.Run("GetPromptTokens_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeLocateResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPromptTokens() // Should return zero value
	})

}

func TestSettersMarkExplicitAccessibilityTreeLocateResponse(t *testing.T) {
	t.Run("SetCompletionTokens_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueCompletionTokens *int

		// Act
		obj.SetCompletionTokens(fernTestValueCompletionTokens)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetConfidence_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueConfidence float64

		// Act
		obj.SetConfidence(fernTestValueConfidence)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCostMicrodollars_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueCostMicrodollars int

		// Act
		obj.SetCostMicrodollars(fernTestValueCostMicrodollars)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFound_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueFound bool

		// Act
		obj.SetFound(fernTestValueFound)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLatencyMs_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueLatencyMs int

		// Act
		obj.SetLatencyMs(fernTestValueLatencyMs)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetModel_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueModel string

		// Act
		obj.SetModel(fernTestValueModel)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNodeID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValueNodeID *string

		// Act
		obj.SetNodeID(fernTestValueNodeID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPromptTokens_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}
		var fernTestValuePromptTokens *int

		// Act
		obj.SetPromptTokens(fernTestValuePromptTokens)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersAccessibilityTreeNode(t *testing.T) {
	t.Run("SetBounds", func(t *testing.T) {
		obj := &AccessibilityTreeNode{}
		var fernTestValueBounds *TreeNodeBounds
		obj.SetBounds(fernTestValueBounds)
		assert.Equal(t, fernTestValueBounds, obj.Bounds)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &AccessibilityTreeNode{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNodeID", func(t *testing.T) {
		obj := &AccessibilityTreeNode{}
		var fernTestValueNodeID string
		obj.SetNodeID(fernTestValueNodeID)
		assert.Equal(t, fernTestValueNodeID, obj.NodeID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPlatform", func(t *testing.T) {
		obj := &AccessibilityTreeNode{}
		var fernTestValuePlatform map[string]any
		obj.SetPlatform(fernTestValuePlatform)
		assert.Equal(t, fernTestValuePlatform, obj.Platform)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRole", func(t *testing.T) {
		obj := &AccessibilityTreeNode{}
		var fernTestValueRole string
		obj.SetRole(fernTestValueRole)
		assert.Equal(t, fernTestValueRole, obj.Role)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetValue", func(t *testing.T) {
		obj := &AccessibilityTreeNode{}
		var fernTestValueValue *string
		obj.SetValue(fernTestValueValue)
		assert.Equal(t, fernTestValueValue, obj.Value)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersAccessibilityTreeNode(t *testing.T) {
	t.Run("GetBounds", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		var expected *TreeNodeBounds
		obj.Bounds = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBounds(), "getter should return the property value")
	})

	t.Run("GetBounds_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		obj.Bounds = nil

		// Act & Assert
		assert.Nil(t, obj.GetBounds(), "getter should return nil when property is nil")
	})

	t.Run("GetBounds_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeNode
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBounds() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeNode
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetNodeID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		var expected string
		obj.NodeID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNodeID(), "getter should return the property value")
	})

	t.Run("GetNodeID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeNode
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNodeID() // Should return zero value
	})

	t.Run("GetPlatform", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		var expected map[string]any
		obj.Platform = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPlatform(), "getter should return the property value")
	})

	t.Run("GetPlatform_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		obj.Platform = nil

		// Act & Assert
		assert.Nil(t, obj.GetPlatform(), "getter should return nil when property is nil")
	})

	t.Run("GetPlatform_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeNode
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPlatform() // Should return zero value
	})

	t.Run("GetRole", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		var expected string
		obj.Role = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRole(), "getter should return the property value")
	})

	t.Run("GetRole_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeNode
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRole() // Should return zero value
	})

	t.Run("GetValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		var expected *string
		obj.Value = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetValue(), "getter should return the property value")
	})

	t.Run("GetValue_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		obj.Value = nil

		// Act & Assert
		assert.Nil(t, obj.GetValue(), "getter should return nil when property is nil")
	})

	t.Run("GetValue_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeNode
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetValue() // Should return zero value
	})

}

func TestSettersMarkExplicitAccessibilityTreeNode(t *testing.T) {
	t.Run("SetBounds_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		var fernTestValueBounds *TreeNodeBounds

		// Act
		obj.SetBounds(fernTestValueBounds)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNodeID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		var fernTestValueNodeID string

		// Act
		obj.SetNodeID(fernTestValueNodeID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPlatform_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		var fernTestValuePlatform map[string]any

		// Act
		obj.SetPlatform(fernTestValuePlatform)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRole_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		var fernTestValueRole string

		// Act
		obj.SetRole(fernTestValueRole)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetValue_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}
		var fernTestValueValue *string

		// Act
		obj.SetValue(fernTestValueValue)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersTreeNodeBounds(t *testing.T) {
	t.Run("SetHeight", func(t *testing.T) {
		obj := &TreeNodeBounds{}
		var fernTestValueHeight int
		obj.SetHeight(fernTestValueHeight)
		assert.Equal(t, fernTestValueHeight, obj.Height)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWidth", func(t *testing.T) {
		obj := &TreeNodeBounds{}
		var fernTestValueWidth int
		obj.SetWidth(fernTestValueWidth)
		assert.Equal(t, fernTestValueWidth, obj.Width)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetX", func(t *testing.T) {
		obj := &TreeNodeBounds{}
		var fernTestValueX int
		obj.SetX(fernTestValueX)
		assert.Equal(t, fernTestValueX, obj.X)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetY", func(t *testing.T) {
		obj := &TreeNodeBounds{}
		var fernTestValueY int
		obj.SetY(fernTestValueY)
		assert.Equal(t, fernTestValueY, obj.Y)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersTreeNodeBounds(t *testing.T) {
	t.Run("GetHeight", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TreeNodeBounds{}
		var expected int
		obj.Height = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHeight(), "getter should return the property value")
	})

	t.Run("GetHeight_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TreeNodeBounds
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHeight() // Should return zero value
	})

	t.Run("GetWidth", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TreeNodeBounds{}
		var expected int
		obj.Width = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWidth(), "getter should return the property value")
	})

	t.Run("GetWidth_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TreeNodeBounds
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWidth() // Should return zero value
	})

	t.Run("GetX", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TreeNodeBounds{}
		var expected int
		obj.X = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetX(), "getter should return the property value")
	})

	t.Run("GetX_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TreeNodeBounds
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetX() // Should return zero value
	})

	t.Run("GetY", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TreeNodeBounds{}
		var expected int
		obj.Y = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetY(), "getter should return the property value")
	})

	t.Run("GetY_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TreeNodeBounds
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetY() // Should return zero value
	})

}

func TestSettersMarkExplicitTreeNodeBounds(t *testing.T) {
	t.Run("SetHeight_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TreeNodeBounds{}
		var fernTestValueHeight int

		// Act
		obj.SetHeight(fernTestValueHeight)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWidth_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TreeNodeBounds{}
		var fernTestValueWidth int

		// Act
		obj.SetWidth(fernTestValueWidth)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetX_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TreeNodeBounds{}
		var fernTestValueX int

		// Act
		obj.SetX(fernTestValueX)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetY_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TreeNodeBounds{}
		var fernTestValueY int

		// Act
		obj.SetY(fernTestValueY)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingAccessibilityTreeLocateResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeLocateResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled AccessibilityTreeLocateResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj AccessibilityTreeLocateResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj AccessibilityTreeLocateResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingAccessibilityTreeNode(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &AccessibilityTreeNode{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled AccessibilityTreeNode
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj AccessibilityTreeNode
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj AccessibilityTreeNode
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingTreeNodeBounds(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &TreeNodeBounds{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled TreeNodeBounds
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj TreeNodeBounds
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj TreeNodeBounds
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringAccessibilityTreeLocateResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &AccessibilityTreeLocateResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeLocateResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringAccessibilityTreeNode(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &AccessibilityTreeNode{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeNode
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringTreeNodeBounds(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &TreeNodeBounds{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TreeNodeBounds
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesAccessibilityTreeLocateResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &AccessibilityTreeLocateResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeLocateResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesAccessibilityTreeNode(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &AccessibilityTreeNode{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *AccessibilityTreeNode
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesTreeNodeBounds(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &TreeNodeBounds{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *TreeNodeBounds
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
