// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/axilioai/platform-go/argus/internal"
	big "math/big"
)

var (
	inferenceRequestFieldConfidenceThreshold = big.NewInt(1 << 0)
	inferenceRequestFieldImage               = big.NewInt(1 << 1)
	inferenceRequestFieldInferenceType       = big.NewInt(1 << 2)
	inferenceRequestFieldNmsIouThreshold     = big.NewInt(1 << 3)
	inferenceRequestFieldOcrEngine           = big.NewInt(1 << 4)
)

type InferenceRequest struct {
	// Minimum confidence threshold for detections and OCR results
	ConfidenceThreshold *float64 `json:"confidence_threshold,omitempty" url:"-"`
	// Base64 encoded image data
	Image string `json:"image" url:"-"`
	// Type of inference to perform
	InferenceType *InferenceType `json:"inference_type,omitempty" url:"-"`
	// IoU threshold for Non-Maximum Suppression (NMS)
	NmsIouThreshold *float64 `json:"nms_iou_threshold,omitempty" url:"-"`
	// OCR engine to use: 'free' or 'premium'
	OcrEngine *string `json:"ocr_engine,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InferenceRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetConfidenceThreshold sets the ConfidenceThreshold field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceRequest) SetConfidenceThreshold(confidenceThreshold *float64) {
	i.ConfidenceThreshold = confidenceThreshold
	i.require(inferenceRequestFieldConfidenceThreshold)
}

// SetImage sets the Image field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceRequest) SetImage(image string) {
	i.Image = image
	i.require(inferenceRequestFieldImage)
}

// SetInferenceType sets the InferenceType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceRequest) SetInferenceType(inferenceType *InferenceType) {
	i.InferenceType = inferenceType
	i.require(inferenceRequestFieldInferenceType)
}

// SetNmsIouThreshold sets the NmsIouThreshold field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceRequest) SetNmsIouThreshold(nmsIouThreshold *float64) {
	i.NmsIouThreshold = nmsIouThreshold
	i.require(inferenceRequestFieldNmsIouThreshold)
}

// SetOcrEngine sets the OcrEngine field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceRequest) SetOcrEngine(ocrEngine *string) {
	i.OcrEngine = ocrEngine
	i.require(inferenceRequestFieldOcrEngine)
}

func (i *InferenceRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler InferenceRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*i = InferenceRequest(body)
	return nil
}

func (i *InferenceRequest) MarshalJSON() ([]byte, error) {
	type embed InferenceRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	locateRequestFieldImage = big.NewInt(1 << 0)
	locateRequestFieldModel = big.NewInt(1 << 1)
	locateRequestFieldQuery = big.NewInt(1 << 2)
	locateRequestFieldTexts = big.NewInt(1 << 3)
)

type LocateRequest struct {
	// Base64 encoded image (PNG or JPEG)
	Image string `json:"image" url:"-"`
	// VLM model to use; must be one of the models from GET /vision/models. Omit to use the server's configured default. The system prompt is fixed to the element-locator task.
	Model *string `json:"model,omitempty" url:"-"`
	// Natural-language target description
	Query string `json:"query" url:"-"`
	// Pre-computed OCR text elements. Empty list means Argus skips OCR grounding and asks the VLM to locate from the image alone.
	Texts []*TextElementInput `json:"texts,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LocateRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetImage sets the Image field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateRequest) SetImage(image string) {
	l.Image = image
	l.require(locateRequestFieldImage)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateRequest) SetModel(model *string) {
	l.Model = model
	l.require(locateRequestFieldModel)
}

// SetQuery sets the Query field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateRequest) SetQuery(query string) {
	l.Query = query
	l.require(locateRequestFieldQuery)
}

// SetTexts sets the Texts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateRequest) SetTexts(texts []*TextElementInput) {
	l.Texts = texts
	l.require(locateRequestFieldTexts)
}

func (l *LocateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler LocateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*l = LocateRequest(body)
	return nil
}

func (l *LocateRequest) MarshalJSON() ([]byte, error) {
	type embed LocateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	boundingBoxFieldX1 = big.NewInt(1 << 0)
	boundingBoxFieldX2 = big.NewInt(1 << 1)
	boundingBoxFieldY1 = big.NewInt(1 << 2)
	boundingBoxFieldY2 = big.NewInt(1 << 3)
)

type BoundingBox struct {
	// Top-left x coordinate
	X1 float64 `json:"x1" url:"x1"`
	// Bottom-right x coordinate
	X2 float64 `json:"x2" url:"x2"`
	// Top-left y coordinate
	Y1 float64 `json:"y1" url:"y1"`
	// Bottom-right y coordinate
	Y2 float64 `json:"y2" url:"y2"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BoundingBox) GetX1() float64 {
	if b == nil {
		return 0
	}
	return b.X1
}

func (b *BoundingBox) GetX2() float64 {
	if b == nil {
		return 0
	}
	return b.X2
}

func (b *BoundingBox) GetY1() float64 {
	if b == nil {
		return 0
	}
	return b.Y1
}

func (b *BoundingBox) GetY2() float64 {
	if b == nil {
		return 0
	}
	return b.Y2
}

func (b *BoundingBox) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BoundingBox) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetX1 sets the X1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoundingBox) SetX1(x1 float64) {
	b.X1 = x1
	b.require(boundingBoxFieldX1)
}

// SetX2 sets the X2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoundingBox) SetX2(x2 float64) {
	b.X2 = x2
	b.require(boundingBoxFieldX2)
}

// SetY1 sets the Y1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoundingBox) SetY1(y1 float64) {
	b.Y1 = y1
	b.require(boundingBoxFieldY1)
}

// SetY2 sets the Y2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BoundingBox) SetY2(y2 float64) {
	b.Y2 = y2
	b.require(boundingBoxFieldY2)
}

func (b *BoundingBox) UnmarshalJSON(data []byte) error {
	type unmarshaler BoundingBox
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BoundingBox(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BoundingBox) MarshalJSON() ([]byte, error) {
	type embed BoundingBox
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BoundingBox) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

var (
	contentBoundsFieldBottomY = big.NewInt(1 << 0)
	contentBoundsFieldTopY    = big.NewInt(1 << 1)
)

type ContentBounds struct {
	// Bottom Y coordinate of content area (above nav bar)
	BottomY int `json:"bottom_y" url:"bottom_y"`
	// Top Y coordinate of content area (below notification bar)
	TopY int `json:"top_y" url:"top_y"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ContentBounds) GetBottomY() int {
	if c == nil {
		return 0
	}
	return c.BottomY
}

func (c *ContentBounds) GetTopY() int {
	if c == nil {
		return 0
	}
	return c.TopY
}

func (c *ContentBounds) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ContentBounds) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetBottomY sets the BottomY field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContentBounds) SetBottomY(bottomY int) {
	c.BottomY = bottomY
	c.require(contentBoundsFieldBottomY)
}

// SetTopY sets the TopY field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ContentBounds) SetTopY(topY int) {
	c.TopY = topY
	c.require(contentBoundsFieldTopY)
}

func (c *ContentBounds) UnmarshalJSON(data []byte) error {
	type unmarshaler ContentBounds
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ContentBounds(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ContentBounds) MarshalJSON() ([]byte, error) {
	type embed ContentBounds
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ContentBounds) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	detectionFieldBbox       = big.NewInt(1 << 0)
	detectionFieldClassID    = big.NewInt(1 << 1)
	detectionFieldClassName  = big.NewInt(1 << 2)
	detectionFieldConfidence = big.NewInt(1 << 3)
)

type Detection struct {
	// Bounding box coordinates
	Bbox *BoundingBox `json:"bbox" url:"bbox"`
	// Class ID of detected object
	ClassID int `json:"class_id" url:"class_id"`
	// Class name of detected object
	ClassName string `json:"class_name" url:"class_name"`
	// Detection confidence score
	Confidence float64 `json:"confidence" url:"confidence"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *Detection) GetBbox() *BoundingBox {
	if d == nil {
		return nil
	}
	return d.Bbox
}

func (d *Detection) GetClassID() int {
	if d == nil {
		return 0
	}
	return d.ClassID
}

func (d *Detection) GetClassName() string {
	if d == nil {
		return ""
	}
	return d.ClassName
}

func (d *Detection) GetConfidence() float64 {
	if d == nil {
		return 0
	}
	return d.Confidence
}

func (d *Detection) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *Detection) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetBbox sets the Bbox field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *Detection) SetBbox(bbox *BoundingBox) {
	d.Bbox = bbox
	d.require(detectionFieldBbox)
}

// SetClassID sets the ClassID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *Detection) SetClassID(classID int) {
	d.ClassID = classID
	d.require(detectionFieldClassID)
}

// SetClassName sets the ClassName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *Detection) SetClassName(className string) {
	d.ClassName = className
	d.require(detectionFieldClassName)
}

// SetConfidence sets the Confidence field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *Detection) SetConfidence(confidence float64) {
	d.Confidence = confidence
	d.require(detectionFieldConfidence)
}

func (d *Detection) UnmarshalJSON(data []byte) error {
	type unmarshaler Detection
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = Detection(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *Detection) MarshalJSON() ([]byte, error) {
	type embed Detection
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *Detection) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	hashResultFieldAhash         = big.NewInt(1 << 0)
	hashResultFieldContentBounds = big.NewInt(1 << 1)
	hashResultFieldDhash         = big.NewInt(1 << 2)
	hashResultFieldHistogram     = big.NewInt(1 << 3)
	hashResultFieldPhash         = big.NewInt(1 << 4)
)

type HashResult struct {
	// Average hash of the content area
	Ahash string `json:"ahash" url:"ahash"`
	// Content area bounds used for hashing
	ContentBounds *ContentBounds `json:"content_bounds,omitempty" url:"content_bounds,omitempty"`
	// Difference hash of the content area
	Dhash string `json:"dhash" url:"dhash"`
	// RGB histogram (3 channels, 32 bins each)
	Histogram [][]int `json:"histogram,omitempty" url:"histogram,omitempty"`
	// Perceptual hash of the content area
	Phash string `json:"phash" url:"phash"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (h *HashResult) GetAhash() string {
	if h == nil {
		return ""
	}
	return h.Ahash
}

func (h *HashResult) GetContentBounds() *ContentBounds {
	if h == nil {
		return nil
	}
	return h.ContentBounds
}

func (h *HashResult) GetDhash() string {
	if h == nil {
		return ""
	}
	return h.Dhash
}

func (h *HashResult) GetHistogram() [][]int {
	if h == nil {
		return nil
	}
	return h.Histogram
}

func (h *HashResult) GetPhash() string {
	if h == nil {
		return ""
	}
	return h.Phash
}

func (h *HashResult) GetExtraProperties() map[string]interface{} {
	if h == nil {
		return nil
	}
	return h.extraProperties
}

func (h *HashResult) require(field *big.Int) {
	if h.explicitFields == nil {
		h.explicitFields = big.NewInt(0)
	}
	h.explicitFields.Or(h.explicitFields, field)
}

// SetAhash sets the Ahash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HashResult) SetAhash(ahash string) {
	h.Ahash = ahash
	h.require(hashResultFieldAhash)
}

// SetContentBounds sets the ContentBounds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HashResult) SetContentBounds(contentBounds *ContentBounds) {
	h.ContentBounds = contentBounds
	h.require(hashResultFieldContentBounds)
}

// SetDhash sets the Dhash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HashResult) SetDhash(dhash string) {
	h.Dhash = dhash
	h.require(hashResultFieldDhash)
}

// SetHistogram sets the Histogram field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HashResult) SetHistogram(histogram [][]int) {
	h.Histogram = histogram
	h.require(hashResultFieldHistogram)
}

// SetPhash sets the Phash field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HashResult) SetPhash(phash string) {
	h.Phash = phash
	h.require(hashResultFieldPhash)
}

func (h *HashResult) UnmarshalJSON(data []byte) error {
	type unmarshaler HashResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*h = HashResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *h)
	if err != nil {
		return err
	}
	h.extraProperties = extraProperties
	h.rawJSON = json.RawMessage(data)
	return nil
}

func (h *HashResult) MarshalJSON() ([]byte, error) {
	type embed HashResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*h),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, h.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (h *HashResult) String() string {
	if h == nil {
		return "<nil>"
	}
	if len(h.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(h.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(h); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", h)
}

var (
	inferenceDataFieldHashResult     = big.NewInt(1 << 0)
	inferenceDataFieldIconDetections = big.NewInt(1 << 1)
	inferenceDataFieldMetadata       = big.NewInt(1 << 2)
	inferenceDataFieldOcrResults     = big.NewInt(1 << 3)
)

type InferenceData struct {
	// Image hash of content area
	HashResult *HashResult `json:"hash_result,omitempty" url:"hash_result,omitempty"`
	// Icon detections (YOLO)
	IconDetections []*Detection `json:"icon_detections,omitempty" url:"icon_detections,omitempty"`
	// Inference metadata
	Metadata *InferenceMetadata `json:"metadata" url:"metadata"`
	// OCR text detections
	OcrResults []*OcrResult `json:"ocr_results,omitempty" url:"ocr_results,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InferenceData) GetHashResult() *HashResult {
	if i == nil {
		return nil
	}
	return i.HashResult
}

func (i *InferenceData) GetIconDetections() []*Detection {
	if i == nil {
		return nil
	}
	return i.IconDetections
}

func (i *InferenceData) GetMetadata() *InferenceMetadata {
	if i == nil {
		return nil
	}
	return i.Metadata
}

func (i *InferenceData) GetOcrResults() []*OcrResult {
	if i == nil {
		return nil
	}
	return i.OcrResults
}

func (i *InferenceData) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InferenceData) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetHashResult sets the HashResult field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceData) SetHashResult(hashResult *HashResult) {
	i.HashResult = hashResult
	i.require(inferenceDataFieldHashResult)
}

// SetIconDetections sets the IconDetections field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceData) SetIconDetections(iconDetections []*Detection) {
	i.IconDetections = iconDetections
	i.require(inferenceDataFieldIconDetections)
}

// SetMetadata sets the Metadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceData) SetMetadata(metadata *InferenceMetadata) {
	i.Metadata = metadata
	i.require(inferenceDataFieldMetadata)
}

// SetOcrResults sets the OcrResults field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceData) SetOcrResults(ocrResults []*OcrResult) {
	i.OcrResults = ocrResults
	i.require(inferenceDataFieldOcrResults)
}

func (i *InferenceData) UnmarshalJSON(data []byte) error {
	type unmarshaler InferenceData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InferenceData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InferenceData) MarshalJSON() ([]byte, error) {
	type embed InferenceData
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InferenceData) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	inferenceMetadataFieldIconDetectionsAfterNms  = big.NewInt(1 << 0)
	inferenceMetadataFieldIconDetectionsBeforeNms = big.NewInt(1 << 1)
	inferenceMetadataFieldImageHeight             = big.NewInt(1 << 2)
	inferenceMetadataFieldImageWidth              = big.NewInt(1 << 3)
	inferenceMetadataFieldInferenceTimeMs         = big.NewInt(1 << 4)
	inferenceMetadataFieldOcrNs                   = big.NewInt(1 << 5)
	inferenceMetadataFieldQueueWaitNs             = big.NewInt(1 << 6)
	inferenceMetadataFieldYoloNs                  = big.NewInt(1 << 7)
)

type InferenceMetadata struct {
	// Number of icon detections after NMS filtering
	IconDetectionsAfterNms int `json:"icon_detections_after_nms" url:"icon_detections_after_nms"`
	// Number of icon detections before NMS filtering
	IconDetectionsBeforeNms int `json:"icon_detections_before_nms" url:"icon_detections_before_nms"`
	// Input image height
	ImageHeight int `json:"image_height" url:"image_height"`
	// Input image width
	ImageWidth int `json:"image_width" url:"image_width"`
	// Total inference time in milliseconds
	InferenceTimeMs float64 `json:"inference_time_ms" url:"inference_time_ms"`
	// Nanoseconds spent in OCR
	OcrNs *int `json:"ocr_ns,omitempty" url:"ocr_ns,omitempty"`
	// Nanoseconds the job waited in the inference queue
	QueueWaitNs *int `json:"queue_wait_ns,omitempty" url:"queue_wait_ns,omitempty"`
	// Nanoseconds spent in YOLO detection
	YoloNs *int `json:"yolo_ns,omitempty" url:"yolo_ns,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InferenceMetadata) GetIconDetectionsAfterNms() int {
	if i == nil {
		return 0
	}
	return i.IconDetectionsAfterNms
}

func (i *InferenceMetadata) GetIconDetectionsBeforeNms() int {
	if i == nil {
		return 0
	}
	return i.IconDetectionsBeforeNms
}

func (i *InferenceMetadata) GetImageHeight() int {
	if i == nil {
		return 0
	}
	return i.ImageHeight
}

func (i *InferenceMetadata) GetImageWidth() int {
	if i == nil {
		return 0
	}
	return i.ImageWidth
}

func (i *InferenceMetadata) GetInferenceTimeMs() float64 {
	if i == nil {
		return 0
	}
	return i.InferenceTimeMs
}

func (i *InferenceMetadata) GetOcrNs() *int {
	if i == nil {
		return nil
	}
	return i.OcrNs
}

func (i *InferenceMetadata) GetQueueWaitNs() *int {
	if i == nil {
		return nil
	}
	return i.QueueWaitNs
}

func (i *InferenceMetadata) GetYoloNs() *int {
	if i == nil {
		return nil
	}
	return i.YoloNs
}

func (i *InferenceMetadata) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InferenceMetadata) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetIconDetectionsAfterNms sets the IconDetectionsAfterNms field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceMetadata) SetIconDetectionsAfterNms(iconDetectionsAfterNms int) {
	i.IconDetectionsAfterNms = iconDetectionsAfterNms
	i.require(inferenceMetadataFieldIconDetectionsAfterNms)
}

// SetIconDetectionsBeforeNms sets the IconDetectionsBeforeNms field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceMetadata) SetIconDetectionsBeforeNms(iconDetectionsBeforeNms int) {
	i.IconDetectionsBeforeNms = iconDetectionsBeforeNms
	i.require(inferenceMetadataFieldIconDetectionsBeforeNms)
}

// SetImageHeight sets the ImageHeight field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceMetadata) SetImageHeight(imageHeight int) {
	i.ImageHeight = imageHeight
	i.require(inferenceMetadataFieldImageHeight)
}

// SetImageWidth sets the ImageWidth field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceMetadata) SetImageWidth(imageWidth int) {
	i.ImageWidth = imageWidth
	i.require(inferenceMetadataFieldImageWidth)
}

// SetInferenceTimeMs sets the InferenceTimeMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceMetadata) SetInferenceTimeMs(inferenceTimeMs float64) {
	i.InferenceTimeMs = inferenceTimeMs
	i.require(inferenceMetadataFieldInferenceTimeMs)
}

// SetOcrNs sets the OcrNs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceMetadata) SetOcrNs(ocrNs *int) {
	i.OcrNs = ocrNs
	i.require(inferenceMetadataFieldOcrNs)
}

// SetQueueWaitNs sets the QueueWaitNs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceMetadata) SetQueueWaitNs(queueWaitNs *int) {
	i.QueueWaitNs = queueWaitNs
	i.require(inferenceMetadataFieldQueueWaitNs)
}

// SetYoloNs sets the YoloNs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceMetadata) SetYoloNs(yoloNs *int) {
	i.YoloNs = yoloNs
	i.require(inferenceMetadataFieldYoloNs)
}

func (i *InferenceMetadata) UnmarshalJSON(data []byte) error {
	type unmarshaler InferenceMetadata
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InferenceMetadata(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InferenceMetadata) MarshalJSON() ([]byte, error) {
	type embed InferenceMetadata
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InferenceMetadata) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	inferenceResponseFieldAnalyzerType = big.NewInt(1 << 0)
	inferenceResponseFieldData         = big.NewInt(1 << 1)
	inferenceResponseFieldType         = big.NewInt(1 << 2)
)

type InferenceResponse struct {
	// Analyzer type used
	AnalyzerType *string `json:"analyzer_type,omitempty" url:"analyzer_type,omitempty"`
	// Inference results data
	Data *InferenceData `json:"data" url:"data"`
	// Response type
	Type *string `json:"type,omitempty" url:"type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *InferenceResponse) GetAnalyzerType() *string {
	if i == nil {
		return nil
	}
	return i.AnalyzerType
}

func (i *InferenceResponse) GetData() *InferenceData {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *InferenceResponse) GetType() *string {
	if i == nil {
		return nil
	}
	return i.Type
}

func (i *InferenceResponse) GetExtraProperties() map[string]interface{} {
	if i == nil {
		return nil
	}
	return i.extraProperties
}

func (i *InferenceResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetAnalyzerType sets the AnalyzerType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceResponse) SetAnalyzerType(analyzerType *string) {
	i.AnalyzerType = analyzerType
	i.require(inferenceResponseFieldAnalyzerType)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceResponse) SetData(data *InferenceData) {
	i.Data = data
	i.require(inferenceResponseFieldData)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InferenceResponse) SetType(type_ *string) {
	i.Type = type_
	i.require(inferenceResponseFieldType)
}

func (i *InferenceResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler InferenceResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = InferenceResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *InferenceResponse) MarshalJSON() ([]byte, error) {
	type embed InferenceResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *InferenceResponse) String() string {
	if i == nil {
		return "<nil>"
	}
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type InferenceType string

const (
	InferenceTypeYolo     InferenceType = "yolo"
	InferenceTypeOcr      InferenceType = "ocr"
	InferenceTypeCombined InferenceType = "combined"
)

func NewInferenceTypeFromString(s string) (InferenceType, error) {
	switch s {
	case "yolo":
		return InferenceTypeYolo, nil
	case "ocr":
		return InferenceTypeOcr, nil
	case "combined":
		return InferenceTypeCombined, nil
	}
	var t InferenceType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i InferenceType) Ptr() *InferenceType {
	return &i
}

// Pixel-space bbox returned by the VLM for the located element.
var (
	locateBBoxFieldHeight = big.NewInt(1 << 0)
	locateBBoxFieldWidth  = big.NewInt(1 << 1)
	locateBBoxFieldX      = big.NewInt(1 << 2)
	locateBBoxFieldY      = big.NewInt(1 << 3)
)

type LocateBBox struct {
	// Height in pixels
	Height int `json:"height" url:"height"`
	// Width in pixels
	Width int `json:"width" url:"width"`
	// Top-left x in image pixels
	X int `json:"x" url:"x"`
	// Top-left y in image pixels
	Y int `json:"y" url:"y"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LocateBBox) GetHeight() int {
	if l == nil {
		return 0
	}
	return l.Height
}

func (l *LocateBBox) GetWidth() int {
	if l == nil {
		return 0
	}
	return l.Width
}

func (l *LocateBBox) GetX() int {
	if l == nil {
		return 0
	}
	return l.X
}

func (l *LocateBBox) GetY() int {
	if l == nil {
		return 0
	}
	return l.Y
}

func (l *LocateBBox) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LocateBBox) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetHeight sets the Height field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateBBox) SetHeight(height int) {
	l.Height = height
	l.require(locateBBoxFieldHeight)
}

// SetWidth sets the Width field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateBBox) SetWidth(width int) {
	l.Width = width
	l.require(locateBBoxFieldWidth)
}

// SetX sets the X field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateBBox) SetX(x int) {
	l.X = x
	l.require(locateBBoxFieldX)
}

// SetY sets the Y field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateBBox) SetY(y int) {
	l.Y = y
	l.require(locateBBoxFieldY)
}

func (l *LocateBBox) UnmarshalJSON(data []byte) error {
	type unmarshaler LocateBBox
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LocateBBox(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LocateBBox) MarshalJSON() ([]byte, error) {
	type embed LocateBBox
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LocateBBox) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// Argus /vision/locate response.
//
// Exactly one of `matched_text_index` or `bbox` is populated when
// `found` is True. `matched_text_index` indicates the VLM grounded its
// answer to a specific OCR text element (pixel-accurate bbox available
// via the original `texts` list). `bbox` is a free-form VLM bbox.
var (
	locateResponseFieldBbox             = big.NewInt(1 << 0)
	locateResponseFieldCompletionTokens = big.NewInt(1 << 1)
	locateResponseFieldConfidence       = big.NewInt(1 << 2)
	locateResponseFieldCostMicrodollars = big.NewInt(1 << 3)
	locateResponseFieldFound            = big.NewInt(1 << 4)
	locateResponseFieldLatencyMs        = big.NewInt(1 << 5)
	locateResponseFieldMatchedTextIndex = big.NewInt(1 << 6)
	locateResponseFieldModel            = big.NewInt(1 << 7)
	locateResponseFieldPromptTokens     = big.NewInt(1 << 8)
)

type LocateResponse struct {
	// Pixel-space bbox. None when matched_text_index is set or found=False.
	Bbox *LocateBBox `json:"bbox,omitempty" url:"bbox,omitempty"`
	// Completion (output) tokens the model billed for this call
	CompletionTokens *int `json:"completion_tokens,omitempty" url:"completion_tokens,omitempty"`
	// Model self-reported confidence
	Confidence float64 `json:"confidence" url:"confidence"`
	// Provider-reported cost in microdollars
	CostMicrodollars int `json:"cost_microdollars" url:"cost_microdollars"`
	// Whether the VLM located the target
	Found bool `json:"found" url:"found"`
	// End-to-end VLM call latency
	LatencyMs int `json:"latency_ms" url:"latency_ms"`
	// Index into the request `texts` list when the answer is OCR-grounded.
	MatchedTextIndex *int `json:"matched_text_index,omitempty" url:"matched_text_index,omitempty"`
	// Model identifier returned by the provider
	Model string `json:"model" url:"model"`
	// Prompt (input) tokens the model billed for this call
	PromptTokens *int `json:"prompt_tokens,omitempty" url:"prompt_tokens,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LocateResponse) GetBbox() *LocateBBox {
	if l == nil {
		return nil
	}
	return l.Bbox
}

func (l *LocateResponse) GetCompletionTokens() *int {
	if l == nil {
		return nil
	}
	return l.CompletionTokens
}

func (l *LocateResponse) GetConfidence() float64 {
	if l == nil {
		return 0
	}
	return l.Confidence
}

func (l *LocateResponse) GetCostMicrodollars() int {
	if l == nil {
		return 0
	}
	return l.CostMicrodollars
}

func (l *LocateResponse) GetFound() bool {
	if l == nil {
		return false
	}
	return l.Found
}

func (l *LocateResponse) GetLatencyMs() int {
	if l == nil {
		return 0
	}
	return l.LatencyMs
}

func (l *LocateResponse) GetMatchedTextIndex() *int {
	if l == nil {
		return nil
	}
	return l.MatchedTextIndex
}

func (l *LocateResponse) GetModel() string {
	if l == nil {
		return ""
	}
	return l.Model
}

func (l *LocateResponse) GetPromptTokens() *int {
	if l == nil {
		return nil
	}
	return l.PromptTokens
}

func (l *LocateResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *LocateResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetBbox sets the Bbox field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateResponse) SetBbox(bbox *LocateBBox) {
	l.Bbox = bbox
	l.require(locateResponseFieldBbox)
}

// SetCompletionTokens sets the CompletionTokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateResponse) SetCompletionTokens(completionTokens *int) {
	l.CompletionTokens = completionTokens
	l.require(locateResponseFieldCompletionTokens)
}

// SetConfidence sets the Confidence field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateResponse) SetConfidence(confidence float64) {
	l.Confidence = confidence
	l.require(locateResponseFieldConfidence)
}

// SetCostMicrodollars sets the CostMicrodollars field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateResponse) SetCostMicrodollars(costMicrodollars int) {
	l.CostMicrodollars = costMicrodollars
	l.require(locateResponseFieldCostMicrodollars)
}

// SetFound sets the Found field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateResponse) SetFound(found bool) {
	l.Found = found
	l.require(locateResponseFieldFound)
}

// SetLatencyMs sets the LatencyMs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateResponse) SetLatencyMs(latencyMs int) {
	l.LatencyMs = latencyMs
	l.require(locateResponseFieldLatencyMs)
}

// SetMatchedTextIndex sets the MatchedTextIndex field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateResponse) SetMatchedTextIndex(matchedTextIndex *int) {
	l.MatchedTextIndex = matchedTextIndex
	l.require(locateResponseFieldMatchedTextIndex)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateResponse) SetModel(model string) {
	l.Model = model
	l.require(locateResponseFieldModel)
}

// SetPromptTokens sets the PromptTokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LocateResponse) SetPromptTokens(promptTokens *int) {
	l.PromptTokens = promptTokens
	l.require(locateResponseFieldPromptTokens)
}

func (l *LocateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler LocateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LocateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LocateResponse) MarshalJSON() ([]byte, error) {
	type embed LocateResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *LocateResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

// One supported model and its pricing, as a standard /v1/models catalog row.
var (
	modelInfoFieldContextWindow = big.NewInt(1 << 0)
	modelInfoFieldID            = big.NewInt(1 << 1)
	modelInfoFieldName          = big.NewInt(1 << 2)
	modelInfoFieldObject        = big.NewInt(1 << 3)
	modelInfoFieldOwnedBy       = big.NewInt(1 << 4)
	modelInfoFieldPricing       = big.NewInt(1 << 5)
	modelInfoFieldType          = big.NewInt(1 << 6)
)

type ModelInfo struct {
	// Maximum context window, in tokens.
	ContextWindow int `json:"context_window" url:"context_window"`
	// Model identifier, e.g. 'anthropic/claude-sonnet-4.5' or 'axilio/argus-ocr-pro-1'. VLM ids are passed as `model` to /vision/locate; Axilio ids identify the engine behind /vision/detect calls (selected via `ocr_engine` / `inference_type`) and are what usage rows are labeled with.
	ID string `json:"id" url:"id"`
	// Human-readable model name.
	Name   string           `json:"name" url:"name"`
	Object *ModelInfoObject `json:"object,omitempty" url:"object,omitempty"`
	// Model provider, e.g. 'anthropic' or 'axilio'.
	OwnedBy string        `json:"owned_by" url:"owned_by"`
	Pricing *ModelPricing `json:"pricing" url:"pricing"`
	// Model type: 'vlm' for the vision-language models served by /vision/locate; 'detect', 'ocr', and 'vision' for the Axilio model line behind /vision/detect.
	Type string `json:"type" url:"type"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *ModelInfo) GetContextWindow() int {
	if m == nil {
		return 0
	}
	return m.ContextWindow
}

func (m *ModelInfo) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *ModelInfo) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *ModelInfo) GetObject() *ModelInfoObject {
	if m == nil {
		return nil
	}
	return m.Object
}

func (m *ModelInfo) GetOwnedBy() string {
	if m == nil {
		return ""
	}
	return m.OwnedBy
}

func (m *ModelInfo) GetPricing() *ModelPricing {
	if m == nil {
		return nil
	}
	return m.Pricing
}

func (m *ModelInfo) GetType() string {
	if m == nil {
		return ""
	}
	return m.Type
}

func (m *ModelInfo) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *ModelInfo) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetContextWindow sets the ContextWindow field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModelInfo) SetContextWindow(contextWindow int) {
	m.ContextWindow = contextWindow
	m.require(modelInfoFieldContextWindow)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModelInfo) SetID(id string) {
	m.ID = id
	m.require(modelInfoFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModelInfo) SetName(name string) {
	m.Name = name
	m.require(modelInfoFieldName)
}

// SetObject sets the Object field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModelInfo) SetObject(object *ModelInfoObject) {
	m.Object = object
	m.require(modelInfoFieldObject)
}

// SetOwnedBy sets the OwnedBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModelInfo) SetOwnedBy(ownedBy string) {
	m.OwnedBy = ownedBy
	m.require(modelInfoFieldOwnedBy)
}

// SetPricing sets the Pricing field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModelInfo) SetPricing(pricing *ModelPricing) {
	m.Pricing = pricing
	m.require(modelInfoFieldPricing)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModelInfo) SetType(type_ string) {
	m.Type = type_
	m.require(modelInfoFieldType)
}

func (m *ModelInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler ModelInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = ModelInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *ModelInfo) MarshalJSON() ([]byte, error) {
	type embed ModelInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *ModelInfo) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type ModelInfoObject string

const (
	ModelInfoObjectModel ModelInfoObject = "model"
)

func NewModelInfoObjectFromString(s string) (ModelInfoObject, error) {
	switch s {
	case "model":
		return ModelInfoObjectModel, nil
	}
	var t ModelInfoObject
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m ModelInfoObject) Ptr() *ModelInfoObject {
	return &m
}

// The customer's billed rates in USD.
//
// VLMs price per token (input/output); the Axilio model line prices per
// page, where one screenshot is one page — so per_page reads as the price
// of one call. A rate is "0" when that unit is free for the model.
var (
	modelPricingFieldInput   = big.NewInt(1 << 0)
	modelPricingFieldOutput  = big.NewInt(1 << 1)
	modelPricingFieldPerPage = big.NewInt(1 << 2)
)

type ModelPricing struct {
	// USD per input token.
	Input string `json:"input" url:"input"`
	// USD per output token.
	Output string `json:"output" url:"output"`
	// USD per page (one screenshot = one page) for the per-page-billed Axilio models. Absent for per-token models.
	PerPage *string `json:"per_page,omitempty" url:"per_page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *ModelPricing) GetInput() string {
	if m == nil {
		return ""
	}
	return m.Input
}

func (m *ModelPricing) GetOutput() string {
	if m == nil {
		return ""
	}
	return m.Output
}

func (m *ModelPricing) GetPerPage() *string {
	if m == nil {
		return nil
	}
	return m.PerPage
}

func (m *ModelPricing) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *ModelPricing) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetInput sets the Input field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModelPricing) SetInput(input string) {
	m.Input = input
	m.require(modelPricingFieldInput)
}

// SetOutput sets the Output field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModelPricing) SetOutput(output string) {
	m.Output = output
	m.require(modelPricingFieldOutput)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *ModelPricing) SetPerPage(perPage *string) {
	m.PerPage = perPage
	m.require(modelPricingFieldPerPage)
}

func (m *ModelPricing) UnmarshalJSON(data []byte) error {
	type unmarshaler ModelPricing
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = ModelPricing(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *ModelPricing) MarshalJSON() ([]byte, error) {
	type embed ModelPricing
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *ModelPricing) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	ocrResultFieldBbox       = big.NewInt(1 << 0)
	ocrResultFieldConfidence = big.NewInt(1 << 1)
	ocrResultFieldText       = big.NewInt(1 << 2)
)

type OcrResult struct {
	// Bounding box around text region
	Bbox *BoundingBox `json:"bbox" url:"bbox"`
	// OCR confidence score
	Confidence float64 `json:"confidence" url:"confidence"`
	// Detected text content
	Text string `json:"text" url:"text"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OcrResult) GetBbox() *BoundingBox {
	if o == nil {
		return nil
	}
	return o.Bbox
}

func (o *OcrResult) GetConfidence() float64 {
	if o == nil {
		return 0
	}
	return o.Confidence
}

func (o *OcrResult) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}

func (o *OcrResult) GetExtraProperties() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.extraProperties
}

func (o *OcrResult) require(field *big.Int) {
	if o.explicitFields == nil {
		o.explicitFields = big.NewInt(0)
	}
	o.explicitFields.Or(o.explicitFields, field)
}

// SetBbox sets the Bbox field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OcrResult) SetBbox(bbox *BoundingBox) {
	o.Bbox = bbox
	o.require(ocrResultFieldBbox)
}

// SetConfidence sets the Confidence field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OcrResult) SetConfidence(confidence float64) {
	o.Confidence = confidence
	o.require(ocrResultFieldConfidence)
}

// SetText sets the Text field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (o *OcrResult) SetText(text string) {
	o.Text = text
	o.require(ocrResultFieldText)
}

func (o *OcrResult) UnmarshalJSON(data []byte) error {
	type unmarshaler OcrResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OcrResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OcrResult) MarshalJSON() ([]byte, error) {
	type embed OcrResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*o),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, o.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (o *OcrResult) String() string {
	if o == nil {
		return "<nil>"
	}
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

// Response for GET /vision/models.
//
// Lists every model Argus supports, each with its final post-markup
// pricing: the curated VLMs for the element-locator task (per-token
// pricing; pass their id as `model` to /vision/locate) and the Axilio
// model line behind /vision/detect (per-page pricing; selected via the
// `ocr_engine` and `inference_type` request fields — lite = the free
// engine, pro = premium). Lets a client compare cost and validate
// `find(model=...)` up front instead of round-tripping to /locate and
// getting a 400.
//
// The VLM set is curated: `/locate` enforces it — an unsupported model is
// rejected, so this is the authoritative allowlist, not just advisory.
// The Axilio ids are not /locate targets.
//
// Shaped like a standard /v1/models response ({object: "list", data: [...]}).
var (
	supportedModelsResponseFieldData   = big.NewInt(1 << 0)
	supportedModelsResponseFieldObject = big.NewInt(1 << 1)
)

type SupportedModelsResponse struct {
	// Supported models, sorted by id.
	Data   []*ModelInfo                   `json:"data" url:"data"`
	Object *SupportedModelsResponseObject `json:"object,omitempty" url:"object,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SupportedModelsResponse) GetData() []*ModelInfo {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s *SupportedModelsResponse) GetObject() *SupportedModelsResponseObject {
	if s == nil {
		return nil
	}
	return s.Object
}

func (s *SupportedModelsResponse) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SupportedModelsResponse) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SupportedModelsResponse) SetData(data []*ModelInfo) {
	s.Data = data
	s.require(supportedModelsResponseFieldData)
}

// SetObject sets the Object field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SupportedModelsResponse) SetObject(object *SupportedModelsResponseObject) {
	s.Object = object
	s.require(supportedModelsResponseFieldObject)
}

func (s *SupportedModelsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SupportedModelsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SupportedModelsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SupportedModelsResponse) MarshalJSON() ([]byte, error) {
	type embed SupportedModelsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SupportedModelsResponse) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SupportedModelsResponseObject string

const (
	SupportedModelsResponseObjectList SupportedModelsResponseObject = "list"
)

func NewSupportedModelsResponseObjectFromString(s string) (SupportedModelsResponseObject, error) {
	switch s {
	case "list":
		return SupportedModelsResponseObjectList, nil
	}
	var t SupportedModelsResponseObject
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SupportedModelsResponseObject) Ptr() *SupportedModelsResponseObject {
	return &s
}

// OCR-detected text element to seed the VLM's grounding context.
var (
	textElementInputFieldBbox = big.NewInt(1 << 0)
	textElementInputFieldText = big.NewInt(1 << 1)
)

type TextElementInput struct {
	// Normalized [0, 1] bbox in the source image
	Bbox *BoundingBox `json:"bbox" url:"bbox"`
	// OCR'd text content
	Text string `json:"text" url:"text"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TextElementInput) GetBbox() *BoundingBox {
	if t == nil {
		return nil
	}
	return t.Bbox
}

func (t *TextElementInput) GetText() string {
	if t == nil {
		return ""
	}
	return t.Text
}

func (t *TextElementInput) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TextElementInput) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetBbox sets the Bbox field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TextElementInput) SetBbox(bbox *BoundingBox) {
	t.Bbox = bbox
	t.require(textElementInputFieldBbox)
}

// SetText sets the Text field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TextElementInput) SetText(text string) {
	t.Text = text
	t.require(textElementInputFieldText)
}

func (t *TextElementInput) UnmarshalJSON(data []byte) error {
	type unmarshaler TextElementInput
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TextElementInput(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TextElementInput) MarshalJSON() ([]byte, error) {
	type embed TextElementInput
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TextElementInput) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
