// Code generated by Fern. DO NOT EDIT.

package runs

import (
	context "context"

	platformgo "github.com/axilioai/platform-go"
	core "github.com/axilioai/platform-go/core"
	internal "github.com/axilioai/platform-go/internal"
	option "github.com/axilioai/platform-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns paginated recent runs for the caller's org. Filters: workflow, search text, status, trigger; sort by any of the columns listed in RunSortField.
func (c *Client) List(
	ctx context.Context,
	request *platformgo.RunListRequest,
	opts ...option.RequestOption,
) (*platformgo.RunListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns paginated run events for a session, filtered by session_id.
func (c *Client) ListEvents(
	ctx context.Context,
	request *platformgo.RunEventsRequest,
	opts ...option.RequestOption,
) (*platformgo.RunEventsResponse, error) {
	response, err := c.WithRawResponse.ListEvents(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns paginated historic runs for the caller's user. Use POST /runs for recent (non-archived) runs.
func (c *Client) ListHistoric(
	ctx context.Context,
	request *platformgo.RunHistoryRequest,
	opts ...option.RequestOption,
) (*platformgo.RunHistoryResponse, error) {
	response, err := c.WithRawResponse.ListHistoric(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns total run count + success rate for the given workflow, scoped to the caller's user.
func (c *Client) Stats(
	ctx context.Context,
	request *platformgo.RunsStatsRequest,
	opts ...option.RequestOption,
) (*platformgo.RunStatsResponse, error) {
	response, err := c.WithRawResponse.Stats(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns one run by ID, scoped to the caller's organization.
func (c *Client) Get(
	ctx context.Context,
	request *platformgo.RunsGetRequest,
	opts ...option.RequestOption,
) (*platformgo.RunResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Transitions a run to CANCELLED, scoped to the caller's org.
func (c *Client) Cancel(
	ctx context.Context,
	request *platformgo.RunsCancelRequest,
	opts ...option.RequestOption,
) (*platformgo.RunSuccessResponse, error) {
	response, err := c.WithRawResponse.Cancel(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates one or more runs against the given workflow and queues them for execution. Pre-flight checks: balance sufficient, concurrency limit, workflow exists. Runs that fail to queue are marked FAILED immediately so they stop counting toward the concurrency limit.
func (c *Client) Create(
	ctx context.Context,
	request *platformgo.RunCreateRequest,
	opts ...option.RequestOption,
) (*platformgo.RunCreateResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
