// Code generated by Fern. DO NOT EDIT.

package billing

import (
	context "context"

	platformgo "github.com/axilioai/platform-go"
	core "github.com/axilioai/platform-go/core"
	internal "github.com/axilioai/platform-go/internal"
	option "github.com/axilioai/platform-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns the organization's automatic balance top-up configuration and status.
func (c *Client) GetAutoRecharge(
	ctx context.Context,
	opts ...option.RequestOption,
) (*platformgo.SubscriptionAutoRechargeSettingsResponse, error) {
	response, err := c.WithRawResponse.GetAutoRecharge(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the organization's current credit balance in microdollars plus a display string.
func (c *Client) GetBalance(
	ctx context.Context,
	opts ...option.RequestOption,
) (*platformgo.SubscriptionBalanceResponse, error) {
	response, err := c.WithRawResponse.GetBalance(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Paginated invoice history for the caller's organization with optional filters and sort.
func (c *Client) GetHistory(
	ctx context.Context,
	request *platformgo.BillingGetHistoryRequest,
	opts ...option.RequestOption,
) (*platformgo.BillingHistoryResponse, error) {
	response, err := c.WithRawResponse.GetHistory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns every phone rental subscription owned by the caller's organization, in any lifecycle state (active or canceled) - canceled rentals are included so past rentals stay visible. Each item's status field tells them apart. The summary block (active_count, combined monthly cost) counts only active rentals.
func (c *Client) GetRentalSubscriptions(
	ctx context.Context,
	opts ...option.RequestOption,
) (*platformgo.PhoneRentalSubscriptionListResponse, error) {
	response, err := c.WithRawResponse.GetRentalSubscriptions(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the caller organization's active subscription plan. Only an active subscription is returned; if the org has none, this responds 404. (The status field is therefore always 'active' here.)
func (c *Client) GetSubscription(
	ctx context.Context,
	opts ...option.RequestOption,
) (*platformgo.SubscriptionResponse, error) {
	response, err := c.WithRawResponse.GetSubscription(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
