// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/axilioai/platform-go/argus/core"
	internal "github.com/axilioai/platform-go/argus/internal"
	option "github.com/axilioai/platform-go/argus/option"
	vision "github.com/axilioai/platform-go/argus/vision"
)

type Client struct {
	Vision *vision.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Vision:  vision.NewClient(options),
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
