// Code generated by scripts/gen_dcp_wire.go from contracts/dcp-asyncapi.json; DO NOT EDIT.

package mobile

// protocolVersion is the DCP revision this layer was generated against.
const protocolVersion = 1

// DCP command method names ("Domain.method").
const (
	methodDeviceInfo        = "Device.info"
	methodKeyboardKeyPress  = "Keyboard.keyPress"
	methodKeyboardTypeText  = "Keyboard.typeText"
	methodProtocolHandshake = "Protocol.handshake"
	methodScreenFind        = "Screen.find"
	methodScreenObserve     = "Screen.observe"
	methodScreenScreenshot  = "Screen.screenshot"
	methodTouchLongPress    = "Touch.longPress"
	methodTouchSwipe        = "Touch.swipe"
	methodTouchTap          = "Touch.tap"
)

// DCP error kinds (the data.kind on a CDP error frame).
const (
	kindCanceled        = "Canceled"
	kindDeviceOffline   = "DeviceOffline"
	kindElementNotFound = "ElementNotFound"
	kindInternal        = "Internal"
	kindInvalidArgs     = "InvalidArgs"
	kindNoAllocation    = "NoAllocation"
	kindNotConnected    = "NotConnected"
	kindTimeout         = "Timeout"
	kindUnauthorized    = "Unauthorized"
	kindUnknownOp       = "UnknownOp"
)

// Input param frames (snake_case on the wire), one per contract schema.
type tapParams struct {
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
	X              int    `json:"x"`
	Y              int    `json:"y"`
}

type longPressParams struct {
	DurationMs     int    `json:"duration_ms,omitempty"`
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
	X              int    `json:"x"`
	Y              int    `json:"y"`
}

type swipeParams struct {
	DurationMs     int    `json:"duration_ms,omitempty"`
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
	X1             int    `json:"x1"`
	X2             int    `json:"x2"`
	Y1             int    `json:"y1"`
	Y2             int    `json:"y2"`
}

type typeTextParams struct {
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
	Text           string `json:"text"`
}

type keyPressParams struct {
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
	Key            string `json:"key,omitempty"`
	Usage          int    `json:"usage,omitempty"`
}

type observeParams struct {
	OcrEngine string `json:"ocr_engine,omitempty"`
}

type findParams struct {
	Model     string `json:"model,omitempty"`
	OcrEngine string `json:"ocr_engine,omitempty"`
	Query     string `json:"query"`
}

type handshakeParams struct {
	ClientVersion string `json:"client_version,omitempty"`
	MinProtocol   int    `json:"min_protocol,omitempty"`
}
