// Code generated by scripts/gen_dcp_wire.go from contracts/dcp-asyncapi.json; DO NOT EDIT.

package mobile

// protocolVersion is the DCP revision this layer was generated against.
const protocolVersion = 1

// DCP command method names ("Domain.method").
const (
	methodAccessibilityDisable          = "Accessibility.disable"
	methodAccessibilityEnable           = "Accessibility.enable"
	methodAccessibilityGetChildAXNodes  = "Accessibility.getChildAXNodes"
	methodAccessibilityGetFullAXTree    = "Accessibility.getFullAXTree"
	methodAccessibilityGetPartialAXTree = "Accessibility.getPartialAXTree"
	methodAccessibilityGetState         = "Accessibility.getState"
	methodAccessibilityQueryAXTree      = "Accessibility.queryAXTree"
	methodDeviceInfo                    = "Device.info"
	methodKeyboardKeyPress              = "Keyboard.keyPress"
	methodKeyboardTypeText              = "Keyboard.typeText"
	methodLocatorBoundingBox            = "Locator.boundingBox"
	methodLocatorCount                  = "Locator.count"
	methodLocatorFill                   = "Locator.fill"
	methodLocatorPress                  = "Locator.press"
	methodLocatorTap                    = "Locator.tap"
	methodLocatorText                   = "Locator.text"
	methodLocatorWaitFor                = "Locator.waitFor"
	methodProtocolHandshake             = "Protocol.handshake"
	methodScreenObserve                 = "Screen.observe"
	methodScreenScreenshot              = "Screen.screenshot"
	methodTouchLongPress                = "Touch.longPress"
	methodTouchSwipe                    = "Touch.swipe"
	methodTouchTap                      = "Touch.tap"
)

// DCP error kinds (the data.kind on a CDP error frame).
const (
	kindActionTimeout       = "ActionTimeout"
	kindCanceled            = "Canceled"
	kindDeviceOffline       = "DeviceOffline"
	kindInternal            = "Internal"
	kindInvalidArgs         = "InvalidArgs"
	kindNoAllocation        = "NoAllocation"
	kindNotConnected        = "NotConnected"
	kindStaleNode           = "StaleNode"
	kindStrategyUnavailable = "StrategyUnavailable"
	kindTimeout             = "Timeout"
	kindTreeUnavailable     = "TreeUnavailable"
	kindUnauthorized        = "Unauthorized"
	kindUnknownOp           = "UnknownOp"
)

// Nested object schemas a locator param frame references (locator.go builds
// these from the hand-written Locator via toWire).
type androidLocatorWire struct {
	ClassName   string `json:"className,omitempty"`
	PackageName string `json:"packageName,omitempty"`
}

type locatorWire struct {
	Exact    bool                 `json:"exact,omitempty"`
	Has      *locatorWire         `json:"has,omitempty"`
	Id       string               `json:"id,omitempty"`
	Name     string               `json:"name,omitempty"`
	NodeId   string               `json:"nodeId,omitempty"`
	Nth      *int                 `json:"nth,omitempty"`
	Platform *locatorPlatformWire `json:"platform,omitempty"`
	Query    string               `json:"query,omitempty"`
	Role     string               `json:"role,omitempty"`
	States   []string             `json:"states,omitempty"`
	Text     string               `json:"text,omitempty"`
	Value    string               `json:"value,omitempty"`
	WindowId string               `json:"windowId,omitempty"`
	Within   *locatorWire         `json:"within,omitempty"`
}

type locatorPlatformWire struct {
	Android *androidLocatorWire `json:"android,omitempty"`
}

// Input param frames (wire casing per contract: snake_case for the pre-locator
// domains, camelCase for Locator and Accessibility), one per contract schema.
type tapParams struct {
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
	X              int    `json:"x"`
	Y              int    `json:"y"`
}

type longPressParams struct {
	DurationMs     int    `json:"duration_ms,omitempty"`
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
	X              int    `json:"x"`
	Y              int    `json:"y"`
}

type swipeParams struct {
	DurationMs     int    `json:"duration_ms,omitempty"`
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
	X1             int    `json:"x1"`
	X2             int    `json:"x2"`
	Y1             int    `json:"y1"`
	Y2             int    `json:"y2"`
}

type typeTextParams struct {
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
	Text           string `json:"text"`
}

type keyPressParams struct {
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
	Key            string `json:"key,omitempty"`
	Usage          int    `json:"usage,omitempty"`
}

type observeParams struct {
	OcrEngine string `json:"ocr_engine,omitempty"`
}

type handshakeParams struct {
	ClientVersion string `json:"client_version,omitempty"`
	MinProtocol   int    `json:"min_protocol,omitempty"`
}

type locatorTapParams struct {
	IdempotencyKey string       `json:"idempotencyKey,omitempty"`
	Locator        *locatorWire `json:"locator"`
	Model          string       `json:"model,omitempty"`
	OcrEngine      string       `json:"ocrEngine,omitempty"`
	Strategy       string       `json:"strategy,omitempty"`
	TimeoutMs      int          `json:"timeoutMs,omitempty"`
}

type locatorFillParams struct {
	IdempotencyKey string       `json:"idempotencyKey,omitempty"`
	Locator        *locatorWire `json:"locator"`
	Model          string       `json:"model,omitempty"`
	OcrEngine      string       `json:"ocrEngine,omitempty"`
	Strategy       string       `json:"strategy,omitempty"`
	Text           string       `json:"text"`
	TimeoutMs      int          `json:"timeoutMs,omitempty"`
}

type locatorPressParams struct {
	IdempotencyKey string       `json:"idempotencyKey,omitempty"`
	Key            string       `json:"key"`
	Locator        *locatorWire `json:"locator,omitempty"`
	Model          string       `json:"model,omitempty"`
	OcrEngine      string       `json:"ocrEngine,omitempty"`
	Strategy       string       `json:"strategy,omitempty"`
	TimeoutMs      int          `json:"timeoutMs,omitempty"`
}

type locatorWaitForParams struct {
	Locator   *locatorWire `json:"locator"`
	Model     string       `json:"model,omitempty"`
	OcrEngine string       `json:"ocrEngine,omitempty"`
	State     string       `json:"state,omitempty"`
	Strategy  string       `json:"strategy,omitempty"`
	TimeoutMs int          `json:"timeoutMs,omitempty"`
}

type locatorQueryParams struct {
	Locator   *locatorWire `json:"locator"`
	Model     string       `json:"model,omitempty"`
	OcrEngine string       `json:"ocrEngine,omitempty"`
	Strategy  string       `json:"strategy,omitempty"`
	TimeoutMs int          `json:"timeoutMs,omitempty"`
}

type locatorCountParams struct {
	Locator   *locatorWire `json:"locator"`
	Model     string       `json:"model,omitempty"`
	OcrEngine string       `json:"ocrEngine,omitempty"`
	Strategy  string       `json:"strategy,omitempty"`
}

type accessibilityToggleParams struct {
	IdempotencyKey string `json:"idempotencyKey,omitempty"`
}

type getFullAXTreeParams struct {
	Depth           *int   `json:"depth,omitempty"`
	InterestingOnly *bool  `json:"interestingOnly,omitempty"`
	WindowId        string `json:"windowId,omitempty"`
}

type getPartialAXTreeParams struct {
	FetchRelatives *bool  `json:"fetchRelatives,omitempty"`
	NodeId         string `json:"nodeId"`
}

type getChildAXNodesParams struct {
	Id string `json:"id"`
}

type queryAXTreeParams struct {
	AccessibleName string       `json:"accessibleName,omitempty"`
	Role           string       `json:"role,omitempty"`
	Selector       *locatorWire `json:"selector,omitempty"`
}
