//go:build ignore

// Command gen_dcp_wire generates the DCP typed wire layer for the mobile driver
// from the vendored AsyncAPI contract.
//
// It reads contracts/dcp-asyncapi.json (the public DCP contract the backend
// publishes on every production deploy) and writes drivers/mobile/wire_gen.go:
// the command-method name constants, the error-kind constants, the protocol
// version, and one struct per input-param schema. These used to be hand-copied
// from the Go server and drifted silently; now the backend's own drift gate
// forces the contract to equal the server, and drivers/mobile/wire_gen_test.go
// forces this file to equal the contract, so the typed layer can never fall out
// of step with the deployed protocol.
//
// Run it after the vendored contract changes:
//
//	go run scripts/gen_dcp_wire.go
//
// Stdlib only, so it adds no dependency to the SDK module.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

// paramStructs maps a contract params-schema name to the unexported Go struct
// name the driver constructs. Only these input schemas are generated; the
// result shapes are ergonomic-driver glue and stay hand-written.
var paramStructs = []struct{ schema, goName string }{
	{"TouchTapParams", "tapParams"},
	{"TouchLongPressParams", "longPressParams"},
	{"TouchSwipeParams", "swipeParams"},
	{"KeyboardTypeTextParams", "typeTextParams"},
	{"KeyboardKeyPressParams", "keyPressParams"},
	{"ObserveParams", "observeParams"},
	{"FindParams", "findParams"},
	{"HandshakeParams", "handshakeParams"},
}

func main() {
	raw, err := os.ReadFile("contracts/dcp-asyncapi.json")
	must(err)
	var doc map[string]any
	must(json.Unmarshal(raw, &doc))

	messages := doc["components"].(map[string]any)["messages"].(map[string]any)
	schemas := doc["components"].(map[string]any)["schemas"].(map[string]any)
	errTable := doc["x-dcp-error-table"].(map[string]any)
	protocol := doc["info"].(map[string]any)["x-dcp-protocol-version"]

	var methods []string
	for name, m := range messages {
		if mm, ok := m.(map[string]any); ok && mm["x-dcp-kind"] == "command" {
			methods = append(methods, name)
		}
	}
	sort.Strings(methods)

	var kinds []string
	for k := range errTable {
		kinds = append(kinds, k)
	}
	sort.Strings(kinds)

	var b bytes.Buffer
	b.WriteString("// Code generated by scripts/gen_dcp_wire.go from contracts/dcp-asyncapi.json; DO NOT EDIT.\n\n")
	b.WriteString("package mobile\n\n")
	fmt.Fprintf(&b, "// protocolVersion is the DCP revision this layer was generated against.\n")
	fmt.Fprintf(&b, "const protocolVersion = %v\n\n", protocol)

	b.WriteString("// DCP command method names (\"Domain.method\").\n")
	b.WriteString("const (\n")
	for _, m := range methods {
		fmt.Fprintf(&b, "\t%s = %q\n", methodConst(m), m)
	}
	b.WriteString(")\n\n")

	b.WriteString("// DCP error kinds (the data.kind on a CDP error frame).\n")
	b.WriteString("const (\n")
	for _, k := range kinds {
		fmt.Fprintf(&b, "\t%s = %q\n", "kind"+k, k)
	}
	b.WriteString(")\n\n")

	b.WriteString("// Input param frames (snake_case on the wire), one per contract schema.\n")
	for _, ps := range paramStructs {
		schema, ok := schemas[ps.schema].(map[string]any)
		if !ok {
			fail("missing schema " + ps.schema)
		}
		emitStruct(&b, ps.goName, schema)
	}

	out, err := format.Source(b.Bytes())
	must(err)
	// Default output path; the drift test passes a temp path to compare against.
	outPath := "drivers/mobile/wire_gen.go"
	if len(os.Args) > 1 {
		outPath = os.Args[1]
	}
	must(os.WriteFile(outPath, out, 0o644))
	fmt.Printf("wrote %s: %d methods, %d kinds, %d param structs\n",
		outPath, len(methods), len(kinds), len(paramStructs))
}

func emitStruct(b *bytes.Buffer, name string, schema map[string]any) {
	props, _ := schema["properties"].(map[string]any)
	required := map[string]bool{}
	if req, ok := schema["required"].([]any); ok {
		for _, r := range req {
			required[r.(string)] = true
		}
	}
	names := make([]string, 0, len(props))
	for n := range props {
		names = append(names, n)
	}
	sort.Strings(names)

	fmt.Fprintf(b, "type %s struct {\n", name)
	for _, n := range names {
		p := props[n].(map[string]any)
		tag := n
		if !required[n] {
			tag += ",omitempty"
		}
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", pascal(n), goType(p), tag)
	}
	b.WriteString("}\n\n")
}

func goType(p map[string]any) string {
	switch p["type"] {
	case "integer":
		if p["format"] == "int64" {
			return "int64"
		}
		return "int"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	default:
		return "string"
	}
}

// methodConst turns "Touch.longPress" into "methodTouchLongPress".
func methodConst(method string) string {
	dom, op, _ := strings.Cut(method, ".")
	return "method" + upperFirst(dom) + upperFirst(op)
}

// pascal turns a snake_case wire field into a Go field name: "duration_ms" ->
// "DurationMs", "x1" -> "X1", "ocr_engine" -> "OcrEngine".
func pascal(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		parts[i] = upperFirst(p)
	}
	return strings.Join(parts, "")
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func must(err error) {
	if err != nil {
		fail(err.Error())
	}
}

func fail(msg string) {
	fmt.Fprintln(os.Stderr, "gen_dcp_wire:", msg)
	os.Exit(1)
}
