// Code generated by Fern. DO NOT EDIT.

package accessibilitytrees

import (
	context "context"
	http "net/http"

	argus "github.com/axilioai/platform-go/argus"
	core "github.com/axilioai/platform-go/argus/core"
	internal "github.com/axilioai/platform-go/argus/internal"
	option "github.com/axilioai/platform-go/argus/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) AccessibilityTreesLocate(
	ctx context.Context,
	request *argus.AccessibilityTreeLocateRequest,
	opts ...option.RequestOption,
) (*core.Response[*argus.AccessibilityTreeLocateResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://argus.axilio.ai",
	)
	endpointURL := baseURL + "/api/v1/accessibility-trees:locate"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *argus.AccessibilityTreeLocateResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(argus.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*argus.AccessibilityTreeLocateResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
